import os
import json, sys, time, urllib.request
from playwright.sync_api import sync_playwright

from pathlib import Path
S = str(Path(__file__).parent)
BASE = "http://localhost:8099/"
def api(path):
    return json.load(urllib.request.urlopen(BASE + path))
def ha_calls():
    return json.load(urllib.request.urlopen("http://localhost:8123/_calls"))

errors, results = [], []
def check(name, cond, extra=""):
    results.append((name, bool(cond)))
    print(("PASS " if cond else "FAIL ") + name + (f"  [{extra}]" if extra and not cond else ""))

with sync_playwright() as p:
    b = p.chromium.launch(args=["--use-gl=swiftshader", "--enable-unsafe-swiftshader", "--ignore-gpu-blocklist"])
    pg = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
    pg.on("console", lambda m: errors.append(m.text) if m.type == "error" else None)
    pg.on("pageerror", lambda e: errors.append("PAGEERROR " + str(e)))
    pg.goto(BASE + "?debug=1"); pg.wait_for_timeout(1500)

    box = pg.locator("#view").bounding_box()
    cx, cy = box["x"] + box["width"]/2, box["y"] + box["height"]/2
    pg.evaluate("window.__fp.topDown()"); pg.wait_for_timeout(300)

    # --- walls: a 6x4 m room (2 cm... snapped to 25 cm grid); scale: read from two clicks
    pg.click("button[data-tool=wall]")
    pts = [(-150,-100),(150,-100),(150,100),(-150,100),(-150,-100)]
    for x, y in pts:
        pg.mouse.click(cx+x, cy+y); pg.wait_for_timeout(100)
    pg.keyboard.press("Escape")
    lay = pg.evaluate("window.__fp.layout")
    walls = lay["floors"][0]["walls"]
    check("4 walls drawn", len(walls) == 4, len(walls))

    # --- openings: door on wall 0, window on wall 1
    pg.click("button[data-tool=opening]")
    s0 = pg.evaluate(f"window.__fp.screenOf('{walls[0]['id']}')")
    pg.mouse.move(s0["x"], s0["y"]); pg.wait_for_timeout(150)
    pg.mouse.click(s0["x"], s0["y"]); pg.wait_for_timeout(200)
    pg.click("#openingPalette button[data-opening=window]")
    s1 = pg.evaluate(f"window.__fp.screenOf('{walls[1]['id']}')")
    pg.mouse.move(s1["x"], s1["y"]); pg.wait_for_timeout(150)
    pg.mouse.click(s1["x"], s1["y"]); pg.wait_for_timeout(200)
    walls = pg.evaluate("window.__fp.layout")["floors"][0]["walls"]
    ops = [o for w in walls for o in w["openings"]]
    check("door + window placed", sorted(o["type"] for o in ops) == ["door", "window"], ops)
    # overlap must be rejected
    pg.mouse.click(s1["x"], s1["y"]); pg.wait_for_timeout(150)
    walls = pg.evaluate("window.__fp.layout")["floors"][0]["walls"]
    check("overlapping window rejected", sum(len(w["openings"]) for w in walls) == 2)

    # --- GLB upload and placement
    pg.click("button[data-tool=device]")
    pg.set_input_files("#modelFile", f"{S}/tri.glb"); pg.wait_for_timeout(800)
    models = api("api/models")
    check("GLB uploaded", [m["name"] for m in models] == ["tri"], models)
    pg.mouse.click(cx-80, cy+20); pg.wait_for_timeout(500)

    # --- entity-linked devices
    pg.click("#paletteGrid button:nth-child(1)")   # light
    pg.select_option("#entitySelect", "light.wohnzimmer")
    pg.mouse.click(cx-30, cy-20); pg.wait_for_timeout(300)
    pg.click("#paletteGrid button:nth-child(4)")   # sensor
    pg.select_option("#entitySelect", "sensor.temp")
    pg.mouse.click(cx+40, cy-20); pg.wait_for_timeout(300)
    devs = pg.evaluate("window.__fp.layout")["floors"][0]["devices"]
    check("3 devices placed", len(devs) == 3, [d["type"] for d in devs])
    check("custom model device type", any(d["type"] == "glb:tri" for d in devs))
    check("entities bound", {d["entity"] for d in devs} == {"", "light.wohnzimmer", "sensor.temp"}, devs)

    # --- light ball / LED strip devices
    pg.click("button[data-tool=device]"); pg.select_option("#entitySelect", "")
    pg.click('#paletteGrid button:has-text("Lichtkugel")'); pg.mouse.click(cx-120, cy-60); pg.wait_for_timeout(300)
    pg.click('#paletteGrid button:has-text("LED-Streifen")'); pg.mouse.click(cx-120, cy+60); pg.wait_for_timeout(300)
    types = [d["type"] for d in pg.evaluate("window.__fp.layout")["floors"][0]["devices"]]
    check("light ball and LED strip placeable", "orb" in types and "strip" in types, types)

    # --- searchable entity picker in the properties panel
    pg.click("button[data-tool=select]"); pg.mouse.click(cx+40, cy-20); pg.wait_for_timeout(400)
    pg.fill(".entPicker input", "temp"); pg.wait_for_timeout(200)
    opts = pg.eval_on_selector_all(".entPicker .entItem", "els => els.map(e => e.dataset.id)")
    check("entity search filters the list", "sensor.temp" in opts and "light.wohnzimmer" not in opts, opts)
    pg.fill(".entPicker input", "wohnzimmer"); pg.keyboard.press("Enter"); pg.wait_for_timeout(300)
    sel = pg.evaluate("window.__fp.layout")["floors"][0]["devices"]
    check("Enter in search assigns first match", any(d["entity"] == "light.wohnzimmer" for d in sel) and not any(d["entity"] == "sensor.temp" for d in sel), [d["entity"] for d in sel])

    # --- settings: English + light theme + imperial
    pg.click("#settingsBtn"); pg.wait_for_timeout(200)
    pg.fill("#setWallHeight", "2.2"); pg.press("#setWallHeight", "Tab"); pg.wait_for_timeout(400)
    hs = {w["height"] for w in pg.evaluate("window.__fp.layout")["floors"][0]["walls"]}
    check("wall height setting applies to existing walls", hs == {2.2}, hs)
    pg.select_option("#setLanguage", "en"); pg.select_option("#setTheme", "light"); pg.select_option("#setUnits", "imperial")
    pg.wait_for_timeout(600)
    check("language switched", pg.inner_text("button[data-tool=wall]") == "Wall", pg.inner_text("button[data-tool=wall]"))
    check("theme switched", pg.evaluate("document.documentElement.dataset.theme") == "light")
    check("temperature / humidity buttons stay visible in the light theme", pg.is_visible("#modeBar"))
    pg.click("#settingsDialog menu button"); pg.wait_for_timeout(300)
    st = api("api/settings")
    check("settings persisted", st["language"] == "en" and st["theme"] == "light" and st["units"] == "imperial", st)

    # --- live mode: tap light -> popup -> toggle
    pg.click("#modeSwitch button[data-mode=live]"); pg.wait_for_timeout(500)
    light = next(d for d in devs if d["entity"] == "light.wohnzimmer")
    s = pg.evaluate(f"window.__fp.screenOf('{light['id']}')")
    pg.mouse.click(s["x"], s["y"]); pg.wait_for_timeout(400)
    check("live popup shows", pg.is_visible("#livePopup"))
    check("popup has entity", "light.wohnzimmer" in pg.inner_text("#livePopup"), pg.inner_text("#livePopup"))
    check("popup lists the scenes the light belongs to", pg.locator("#livePopup .sceneList button", has_text="Gaming").count() == 1, pg.inner_text("#livePopup"))
    pg.click("#livePopup .actions button:nth-child(3)"); pg.wait_for_timeout(900)
    check("service called", ["light", "toggle", "light.wohnzimmer"] in ha_calls(), ha_calls())
    rid = pg.evaluate("""() => { const f = window.__fp.layout.floors.find(f => f.devices.some(d => d.entity === 'light.wohnzimmer')); const d = f.devices.find(d => d.entity === 'light.wohnzimmer');
      const r = { id: 'rp_test', name: 'Testraum', color: '#8a7f70', points: [[d.x - 3, d.z - 3], [d.x + 3, d.z - 3], [d.x + 3, d.z + 3], [d.x - 3, d.z + 3]] }; f.rooms.push(r); return r.id; }""")
    pg.evaluate(f"window.__fp.openRoomPanel({rid!r})"); pg.wait_for_timeout(300)
    nmore = pg.locator("#roomPanel .rp-more").count()
    if nmore:
        pg.locator("#roomPanel .rp-more").first.click(); pg.wait_for_timeout(300)
    check("room panel unfolds colours and scenes of a light", nmore > 0 and pg.locator("#roomPanel .rp-ctl .swatches").count() == 1, (rid, nmore))
    pg.screenshot(path=f"{S}/live.png")

    # --- persisted and reloadable
    pg.wait_for_timeout(1800)
    pg.goto(BASE + "?debug=1&mode=live"); pg.wait_for_timeout(1500)
    lay = pg.evaluate("window.__fp.layout")["floors"][0]
    check("layout survives reload", len(lay["walls"]) == 4 and len(lay["devices"]) == 5)
    check("reload in live mode", pg.evaluate("document.body.classList.contains('live')"))
    check("live mode shows only 3D (view toggles hidden)", pg.evaluate("document.body.classList.contains('viewlock')") and not pg.is_visible("#view2d") and not pg.is_visible("#viewSplit"))
    api_set = pg.evaluate("fetch('api/settings').then(r=>r.json()).then(s=>fetch('api/settings',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...s,userViews:{admin:'all'}})}).then(r=>r.status))")
    pg.goto(BASE + "?debug=1&mode=live"); pg.wait_for_timeout(1500)
    check("user with view 'all' can switch views in live mode", api_set == 200 and pg.is_visible("#view2d") and pg.is_visible("#viewSplit"), api_set)
    users = pg.evaluate("fetch('api/users').then(r=>r.json())")
    check("users endpoint answers for editors", isinstance(users, list), users)
    pg.click("#modeSwitch button[data-mode=edit]"); pg.wait_for_timeout(300)
    pg.click("#view3d"); pg.wait_for_timeout(600)
    pg.screenshot(path=f"{S}/edit3d.png")
    # --- 2D blueprint editor works on the same layout as the 3D view
    pg2 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
    pg2.on("pageerror", lambda e: errors.append("PAGEERROR " + str(e)))
    pg2.goto(BASE + "?debug=1&mode=edit"); pg2.wait_for_timeout(1500)
    pg2.click("#view2d"); pg2.wait_for_timeout(500)
    check("2D plan visible", pg2.is_visible("#plan2d") and pg2.evaluate("getComputedStyle(document.querySelector('#view')).visibility") == "hidden")
    n0 = len(pg2.evaluate("window.__fp.layout.floors[0].walls"))
    pg2.click("button[data-tool=wall]")
    for (x, z) in [(-2, -2), (-2, 2)]:
        c = pg2.evaluate(f"window.__fp.plan().toClient({x},{z})"); pg2.mouse.click(*c); pg2.wait_for_timeout(100)
    pg2.keyboard.press("Escape")
    n1 = len(pg2.evaluate("window.__fp.layout.floors[0].walls"))
    check("wall drawn in 2D", n1 == n0 + 1, (n0, n1))
    pg2.click("#viewSplit"); pg2.wait_for_timeout(500)
    check("split view shows both", pg2.is_visible("#plan2d") and pg2.evaluate("getComputedStyle(document.querySelector('#view')).visibility") == "visible")
    # --- background image: upload, calibrate scale, move, opacity, remove
    import struct, zlib
    def png(w, h):
        raw = b"".join(b"\x00" + b"\x40\x80\xc0" * w for _ in range(h))
        chunk = lambda t, d: struct.pack(">I", len(d)) + t + d + struct.pack(">I", zlib.crc32(t + d) & 0xffffffff)
        return b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", w, h, 8, 2, 0, 0, 0)) + chunk(b"IDAT", zlib.compress(raw)) + chunk(b"IEND", b"")
    Path(f"{S}/bg.png").write_bytes(png(200, 100))
    pg2.click("#bgPanel > summary"); pg2.wait_for_timeout(200)
    pg2.set_input_files("#bgFile", f"{S}/bg.png"); pg2.wait_for_timeout(900)
    bg = pg2.evaluate("window.__fp.layout.floors[0].bg")
    check("background image uploaded and stored on the floor", bg and bg["ar"] == 0.5 and bg["w"] == 12, bg)
    check("background image is drawn in the 2D plan", pg2.locator("#plan2d image").count() == 1)
    check("background file is served", pg2.evaluate(f"fetch('api/backgrounds/{bg['img']}').then(r => r.headers.get('content-type'))") == "image/png")
    pg2.once("dialog", lambda d: d.accept("13.1234"))   # units are imperial here: 13.1234 ft = 4 m
    pg2.click("#bgCalib"); pg2.wait_for_timeout(200)
    for (x, z) in [(0, 0), (2, 0)]:
        c = pg2.evaluate(f"window.__fp.plan().toClient({x},{z})"); pg2.mouse.click(*c); pg2.wait_for_timeout(150)
    bg = pg2.evaluate("window.__fp.layout.floors[0].bg")
    check("calibration scales the image (2 m clicked = 4 m real -> width x2)", abs(bg["w"] - 24) < 0.5, bg)
    pg2.click("#bgMove"); pg2.wait_for_timeout(200)
    x0 = bg["x"]
    c = pg2.evaluate("window.__fp.plan().toClient(1,1)")
    pg2.mouse.move(*c); pg2.mouse.down(); pg2.mouse.move(c[0] + 80, c[1] + 40, steps=5); pg2.mouse.up(); pg2.wait_for_timeout(200)
    bg2 = pg2.evaluate("window.__fp.layout.floors[0].bg")
    check("image can be dragged", bg2["x"] > x0 + 0.1, (x0, bg2["x"]))
    b3 = pg2.evaluate("window.__fp.layout.floors[0].bg")
    corner = pg2.evaluate(f"window.__fp.plan().toClient({b3['x']},{b3['z']})")          # top-left handle (the far corner is off screen)
    far = lambda b: (b["x"] + b["w"], b["z"] + b["w"] * b["ar"])
    pg2.mouse.move(*corner); pg2.mouse.down(); pg2.mouse.move(corner[0] + 60, corner[1] + 30, steps=6); pg2.mouse.up(); pg2.wait_for_timeout(250)
    b4 = pg2.evaluate("window.__fp.layout.floors[0].bg")
    check("image can be resized at a corner (opposite corner stays)", b4["w"] < b3["w"] - 0.1 and abs(far(b4)[0] - far(b3)[0]) < 0.02 and abs(far(b4)[1] - far(b3)[1]) < 0.02, (b3, b4))
    pg2.keyboard.press("Escape")
    pg2.fill("#bgOpacity", "0.8"); pg2.wait_for_timeout(300)
    check("opacity changes", pg2.evaluate("window.__fp.layout.floors[0].bg.op") == 0.8)
    pg2.wait_for_timeout(1800)
    check("background persisted with the layout", api("api/layout")["floors"][0].get("bg", {}).get("img") == bg["img"])
    pg2.click("#bgRemove"); pg2.wait_for_timeout(200)
    check("background removed", pg2.evaluate("window.__fp.layout.floors[0].bg") is None and pg2.locator("#plan2d image").count() == 0)
    pg2.wait_for_timeout(1800)
    # --- placeholder block for the floor below (created automatically on the first floor)
    fl0 = pg2.evaluate("window.__fp.layout.floors.length")
    pg2.click("button[data-tool=block]"); pg2.wait_for_timeout(200)
    corners = [(-2.5, -2), (2.5, -2), (2.5, 2), (-2.5, 2), (-2.5, -2)]
    for (x, z) in corners:
        c = pg2.evaluate(f"window.__fp.plan().toClient({x},{z})"); pg2.mouse.click(*c); pg2.wait_for_timeout(120)
    lay = pg2.evaluate("window.__fp.layout")
    check("block: floor below created and holds the block", len(lay["floors"]) == fl0 + 1 and len(lay["floors"][0]["blocks"]) == 1 and lay["floors"][1]["walls"], (fl0, len(lay["floors"])))
    check("block is drawn hatched in 2D and exists in 3D", pg2.locator('#plan2d polygon[fill="url(#hatch)"]').count() >= 1 and pg2.evaluate(f"window.__fp.has('{lay['floors'][0]['blocks'][0]['id']}')"))
    # --- stairs: place, flip to 'comes from below' (opening in this floor), stairwell preset, delete, undo
    pg2.click("button[data-tool=stairs]"); pg2.wait_for_timeout(200)
    pg2.click("#stairTypes button[data-stair=U]")
    c = pg2.evaluate("window.__fp.plan().toClient(0,0)"); pg2.mouse.click(*c); pg2.wait_for_timeout(300)
    fl = pg2.evaluate("window.__fp.layout")["floors"][1]
    check("U stair placed and selected", len(fl["stairs"]) == 1 and fl["stairs"][0]["type"] == "U" and pg2.evaluate(f"window.__fp.has('{fl['stairs'][0]['id']}')"), fl["stairs"])
    pg2.select_option("#propsBody select >> nth=0", "down"); pg2.wait_for_timeout(300)
    check("'comes from below' cuts an opening into this floor", pg2.evaluate("window.__fp.layout.floors[1].stairs[0].dir") == "down" and pg2.evaluate("window.__fp.holeCount(1)") == 1)
    w0, r0 = len(fl["walls"]), len(fl["rooms"])
    pg2.click("button[data-tool=stairs]"); pg2.click("#stairTypes button[data-stair=shaft]")
    c = pg2.evaluate("window.__fp.plan().toClient(-1.5,-0.5)"); pg2.mouse.click(*c); pg2.wait_for_timeout(300)
    fl = pg2.evaluate("window.__fp.layout")["floors"][1]
    doors = sum(1 for w in fl["walls"] for o in w["openings"] if o["type"] == "door")
    check("stairwell preset adds 4 walls, a room, a door and a stair", len(fl["walls"]) == w0 + 4 and len(fl["rooms"]) == r0 + 1 and len(fl["stairs"]) == 2 and doors >= 2, (len(fl["walls"]), w0, doors))
    pg2.keyboard.press("Delete"); pg2.wait_for_timeout(200)
    check("stair can be deleted", len(pg2.evaluate("window.__fp.layout.floors[1].stairs")) == 1)
    pg2.keyboard.press("Control+z"); pg2.wait_for_timeout(200)
    check("undo brings the stair back", len(pg2.evaluate("window.__fp.layout.floors[1].stairs")) == 2)
    # --- rooms: double click on an edge adds a corner, double click on a corner removes it
    pg2.click("button[data-tool=room]")
    devs = pg2.evaluate("window.__fp.layout.floors[1].devices.map(d => [d.x, d.z])")
    ox = next(o for o in (-2.4, -1.2, 0.0, 1.2, 2.4, 3.6) if all(abs(dx - (o + 0.6)) > 1.5 or abs(dz - 0.45) > 1.5 for dx, dz in devs))   # a spot without devices (a double click on a device toggles it)
    sq = [(ox, 0.0), (ox + 1.2, 0.0), (ox + 1.2, 0.9), (ox, 0.9), (ox, 0.0)]
    for (x, z) in sq:
        c = pg2.evaluate(f"window.__fp.plan().toClient({x},{z})"); pg2.mouse.click(*c); pg2.wait_for_timeout(100)
    pg2.click("button[data-tool=select]")
    rm = pg2.evaluate("window.__fp.layout.floors[1].rooms.at(-1)")
    pa, pb = rm["points"][0], rm["points"][1]
    mid = pg2.evaluate(f"window.__fp.plan().toClient({(pa[0] + pb[0]) / 2},{(pa[1] + pb[1]) / 2})")
    pg2.mouse.dblclick(*mid); pg2.wait_for_timeout(250)
    rm2 = pg2.evaluate("window.__fp.layout.floors[1].rooms.at(-1)")
    check("double click on a room edge inserts a corner on that edge", len(rm2["points"]) == len(rm["points"]) + 1 and abs(rm2["points"][1][1] - pa[1]) < 0.02, (len(rm["points"]), len(rm2["points"]), rm["points"], rm2["points"], mid, pg2.evaluate("window.__fp.layout.floors[1].rooms.length")))
    p1 = pg2.evaluate(f"window.__fp.plan().toClient({rm2['points'][1][0]},{rm2['points'][1][1]})")
    pg2.mouse.dblclick(*p1); pg2.wait_for_timeout(250)
    rm3 = pg2.evaluate("window.__fp.layout.floors[1].rooms.at(-1)")
    check("double click on a corner removes it again", len(rm3["points"]) == len(rm["points"]), len(rm3["points"]))
    # --- stair opening also cuts a room it only overlaps partly
    pg2.click("button[data-tool=stairs]"); pg2.click("#stairTypes button[data-stair=straight]")
    c = pg2.evaluate(f"window.__fp.plan().toClient({ox - 1.5},0.0)"); pg2.mouse.click(*c); pg2.wait_for_timeout(300)   # its opening reaches half into the new room
    stid = pg2.evaluate("window.__fp.layout.floors[1].stairs.at(-1).id")
    rid2 = pg2.evaluate("window.__fp.layout.floors[1].rooms.at(-1).id")
    v_up = pg2.evaluate(f"window.__fp.roomArea('{rid2}')")
    pg2.select_option("#propsBody select >> nth=0", "down"); pg2.wait_for_timeout(300)
    v_down = pg2.evaluate(f"window.__fp.roomArea('{rid2}')")
    check("stair opening cuts a room it overlaps only partly", v_up and v_down and 0 < v_down < v_up - 0.05, (v_up, v_down))
    # --- stair size: width handle (drag) and length field (typed)
    w0 = pg2.evaluate("window.__fp.layout.floors[1].stairs.at(-1).w")
    hw = pg2.evaluate(f"window.__fp.stairHandle('{stid}','wid')")
    hc = pg2.evaluate(f"window.__fp.plan().toClient({hw[0]},{hw[1]})")
    pg2.mouse.move(*hc); pg2.mouse.down(); pg2.mouse.move(hc[0], hc[1] + 30, steps=5); pg2.mouse.up(); pg2.wait_for_timeout(250)
    w1 = pg2.evaluate("window.__fp.layout.floors[1].stairs.at(-1).w")
    check("stair width can be dragged at its side handle", w1 > w0 + 0.05, (w0, w1))
    t1 = pg2.evaluate("window.__fp.layout.floors[1].stairs.at(-1).tread")
    pg2.locator('#propsBody .prop:has(label:text-is("Length")) input').fill("30"); pg2.keyboard.press("Tab"); pg2.wait_for_timeout(250)
    t2 = pg2.evaluate("window.__fp.layout.floors[1].stairs.at(-1).tread")
    check("stair length can be typed", abs(t2 - t1) > 0.005, (t1, t2))
    # --- door: reverse swing (other side of the wall), independent of flip
    pg2.click("button[data-tool=select]")
    pg2.fill("#objListBody .objfilter", "Door"); pg2.wait_for_timeout(150)
    pg2.locator("#objListBody button.obj", has_text="Door").first.click(); pg2.wait_for_timeout(250)
    pg2.fill("#objListBody .objfilter", ""); pg2.evaluate("document.activeElement.blur()")
    pg2.check("#doorInv"); pg2.wait_for_timeout(250)
    invs = pg2.evaluate("window.__fp.layout.floors[1].walls.flatMap(w => w.openings).filter(o => o.type === 'door').map(o => !!o.inv)")
    check("door swing can be reversed", invs.count(True) == 1 and pg2.locator('#plan2d').is_visible(), invs)
    # --- floors: basement below, move, roof, whole-house view, decoration
    nf = pg2.evaluate("window.__fp.layout.floors.length")
    pg2.evaluate("document.querySelector('#floorPanel').open = true")
    pg2.once("dialog", lambda d: d.accept("Keller"))
    pg2.click("#addBasement"); pg2.wait_for_timeout(300)
    fl = pg2.evaluate("window.__fp.layout.floors.map(f => [f.name, f.kind])")
    check("basement is inserted below all floors", len(fl) == nf + 1 and fl[0] == ["Keller", "basement"], fl)
    e = pg2.evaluate("[window.__fp.elev(0), window.__fp.elev(1)]")
    check("ground floor keeps its height 0, basement is below", e[0] < -2.5 and abs(e[1]) < 1e-6, e)
    pg2.click("#floorUp"); pg2.wait_for_timeout(300)
    fl2 = pg2.evaluate("window.__fp.layout.floors.map(f => f.kind)")
    check("floor can be moved up", fl2[1] == "basement" and fl2[0] != "basement", fl2)
    pg2.click("#floorDown"); pg2.wait_for_timeout(300)
    check("floor can be moved down again", pg2.evaluate("window.__fp.layout.floors[0].kind") == "basement")
    pg2.once("dialog", lambda d: d.accept("Dach"))
    pg2.click("#addRoof"); pg2.wait_for_timeout(300)
    check("roof is added as top floor", pg2.evaluate("window.__fp.layout.floors.at(-1).kind") == "roof" and pg2.locator("#roofType").is_visible())
    pg2.select_option("#roofType", "hip"); pg2.wait_for_timeout(200)
    check("roof shape can be chosen", pg2.evaluate("window.__fp.layout.floors.at(-1).roof.type") == "hip")
    g = pg2.evaluate("window.__fp.layout.floors[1].devices.length")
    pg2.evaluate("""() => { const f = window.__fp.layout.floors[1];
      f.devices.push({id:'t1',type:'tree',x:-6,z:-6,y:0,rot:0,scale:1,name:'Baum',entity:''},{id:'p1',type:'pool',x:-9,z:2,y:0,rot:0,scale:1,name:'Pool',entity:''},{id:'l1',type:'lawn',x:-8,z:-2,y:0,rot:0,scale:1,name:'Rasen',entity:''}); }""")
    pg2.evaluate("""() => { const f = window.__fp.layout.floors[1]; ['panel_tri','panel_hex','panel_sq','panel_bar'].forEach((t, i) => f.devices.push({id:'n'+i,type:t,x:-4+i*0.4,z:-4,y:1.4,rot:0,scale:1,name:'Nano',entity:'light.wohnzimmer'})); }""")
    pg2.evaluate("() => { const d = window.__fp.layout.floors[1].devices.find(v => v.id === 'n0'); d.tiltZ = 60; d.tiltX = 20; d.mirror = true; }")
    pg2.click("#floorPills .pill >> nth=1"); pg2.wait_for_timeout(300)
    oi = pg2.evaluate("window.__fp.objInfo('n0')")
    check("device can be tilted on other axes and mirrored", oi and abs(oi["rz"] - 1.047) < 0.01 and abs(oi["rx"] - 0.349) < 0.01 and oi["sx"] < 0, oi)
    # --- groups: pick two panels with the group tool in 2D, then move / turn / mirror together
    pg2.evaluate("() => { const d = window.__fp.layout.floors[1].devices.find(v => v.id === 'n0'); delete d.tiltZ; delete d.tiltX; delete d.mirror; }")
    pg2.click("#floorPills .pill >> nth=1"); pg2.wait_for_timeout(300)
    pg2.click("button[data-tool=group]"); pg2.wait_for_timeout(200)
    for pid in ("n0", "n1"):
        dv = pg2.evaluate(f"window.__fp.layout.floors[1].devices.find(v => v.id === '{pid}')")
        cc = pg2.evaluate(f"window.__fp.plan().toClient({dv['x']},{dv['z']})")
        pg2.mouse.click(*cc); pg2.wait_for_timeout(200)
    pg2.click("#grpMake"); pg2.wait_for_timeout(300)
    gd = pg2.evaluate("window.__fp.layout.floors[1].devices.filter(v => v.group).map(v => v.id)")
    check("group tool joins the picked devices", sorted(gd) == ["n0", "n1"], gd)
    P = lambda i: pg2.evaluate(f"(() => {{ const d = window.__fp.layout.floors[1].devices.find(v => v.id === '{i}'); return [d.x, d.z, d.rot || 0]; }})()")
    a0, b0 = P("n0"), P("n1")
    pg2.fill("#objListBody .objfilter", "Nano"); pg2.wait_for_timeout(150)
    pg2.click("#objListBody button.obj >> text=Nano >> nth=0"); pg2.wait_for_timeout(300)
    pg2.fill("#objListBody .objfilter", ""); pg2.evaluate("document.activeElement.blur()")
    pg2.keyboard.press("e"); pg2.wait_for_timeout(300)
    a1, b1 = P("n0"), P("n1")
    da, db = ((a1[0]-b1[0])**2 + (a1[1]-b1[1])**2) ** .5, ((a0[0]-b0[0])**2 + (a0[1]-b0[1])**2) ** .5
    check("group turns as one shape (distance kept, both rotated)", abs(da - db) < 1e-3 and a1[2] != a0[2] and b1[2] != b0[2], (a0, b0, a1, b1))
    pg2.click("#grpMirror"); pg2.wait_for_timeout(300)
    pg2.click("#grpMirror"); pg2.wait_for_timeout(300)
    a2, b2 = P("n0"), P("n1")
    check("mirroring the group twice restores it", all(abs(u - v) < 1e-2 for u, v in zip(a1 + b1, a2 + b2)), (a1, b1, a2, b2))
    pg2.click("#grpDissolve"); pg2.wait_for_timeout(300)
    # --- wall stop: a device cannot be pushed through a wall (unless the option is off)
    pg2.evaluate("() => { const f = window.__fp.layout.floors[1]; f.walls.push({id:'wstop',a:[-20,-5],b:[-20,5],thickness:0.2,height:2.6,openings:[]}); f.devices.push({id:'ws1',type:'plant',x:-19,z:0,y:0,rot:0,scale:1,name:'P',entity:''}); }")
    r1 = pg2.evaluate("window.__fp.moveDevice('ws1', -21, 0)")
    r2 = pg2.evaluate("window.__fp.moveDevice('ws1', -19.5, 1)")
    check("device stops at a wall", r1 == [-19, 0] and r2 == [-19.5, 1], (r1, r2))
    r4 = pg2.evaluate("window.__fp.moveDevice('ws1', -19.7, 2)")
    check("device slides along the wall instead of freezing", r4 == [-19.5, 2] or r4 == [-19, 2], r4)
    pg2.evaluate("window.__fp.moveDevice('ws1', -19, 0)")
    pg2.evaluate("window.__fp.layout.floors[1].devices.find(v => v.id === 'ws1').locked = true")
    rl = pg2.evaluate("window.__fp.moveDevice('ws1', -19, 3)")
    check("locked device cannot be moved", rl == [-19, 2] or rl == [-19, 0], rl)
    pg2.evaluate("delete window.__fp.layout.floors[1].devices.find(v => v.id === 'ws1').locked")
    pg2.evaluate("window.__fp.moveDevice('ws1', -19, 0)")
    pg2.evaluate("window.__fp.setWallStop(false)")
    r3 = pg2.evaluate("window.__fp.moveDevice('ws1', -21, 0)")
    pg2.evaluate("window.__fp.setWallStop(true)")
    check("wall stop can be switched off", r3 == [-21, 0], r3)
    pg2.evaluate("() => { const d = window.__fp.layout.floors[1].devices.find(v => v.id === 'ws1'); d.sx = 2; d.sy = 0.5; window.__fp.rebuild(); }"); pg2.wait_for_timeout(400)
    oi = pg2.evaluate("window.__fp.objInfo('ws1')")
    check("device can be stretched independently per axis", oi and abs(oi["sx"] - 2) < 0.01, oi)
    pg2.evaluate("() => { const d = window.__fp.layout.floors[1].devices.find(v => v.id === 'ws1'); delete d.sx; delete d.sy; window.__fp.rebuild(); }")
    check("group can be dissolved", pg2.evaluate("window.__fp.layout.floors[1].devices.filter(v => v.group).length") == 0)
    # --- library: previews, search, categories; door/window styles; pictures on walls
    pg2.click("button[data-tool=device]"); pg2.wait_for_timeout(500)
    nthumb = pg2.locator("#paletteGrid button.dev img").count()
    check("library shows previews for the furniture", nthumb >= 70, nthumb)
    pg2.fill("#paletteSearch", "stove"); pg2.wait_for_timeout(200)
    check("library search finds the stove", pg2.locator("#paletteGrid button.dev").count() == 1, pg2.locator("#paletteGrid button.dev").count())
    pg2.fill("#paletteSearch", "fernseher"); pg2.wait_for_timeout(200)
    check("library search finds a TV by its everyday name (incl. wall TV)", pg2.locator("#paletteGrid button.dev").count() >= 2, pg2.locator("#paletteGrid button.dev").count())
    pg2.fill("#paletteSearch", "")
    pg2.locator("#paletteCats button", has_text="Bath").click(); pg2.wait_for_timeout(200)
    nb = pg2.locator("#paletteGrid button.dev").count()
    check("library category filters", 5 <= nb <= 10, nb)
    pg2.locator("#paletteCats button", has_text="All").click()
    pg2.click("button[data-tool=select]")
    check("12 door and window presets", pg2.locator("#openingPalette button").count() == 12)
    pg2.evaluate("""() => { const f = window.__fp.layout.floors[1], w = f.walls.find(v => v.id === 'wstop');
      [['door','double',1.6,2.05,0,-3],['door','sliding',1.8,2.1,0,-1],['door','open',1.0,2.05,0,1],['window','triple',2.4,1.2,0.9,3.2]].forEach(([type,style,width,height,sill,pos], i) => w.openings.push({id:'op'+i,type,style,width,height,sill,pos:pos+5}));
      f.devices.push({id:'pic1',type:'picture',x:-19.5,z:0,y:1.5,rot:0,scale:1,name:'Bild',entity:'',w:0.8,ar:0.75}); }""")
    up = pg2.evaluate("""async () => { const c = document.createElement('canvas'); c.width = 40; c.height = 30; const x = c.getContext('2d'); x.fillStyle = '#2a7'; x.fillRect(0,0,40,30);
      const blob = await new Promise(r => c.toBlob(r, 'image/png')); const fd = new FormData(); fd.append('file', blob, 'pic.png');
      const r = await fetch('api/backgrounds', {method:'POST', body: fd}); return r.ok ? (await r.json()).name : r.status; }""")
    check("picture image can be uploaded", isinstance(up, str), up)
    pg2.evaluate(f"() => {{ const d = window.__fp.layout.floors[1].devices.find(v => v.id === 'pic1'); d.img = '{up}'; d.ar = 0.75; }}")
    pg2.click("#floorPills .pill >> nth=1"); pg2.wait_for_timeout(800)
    sn = pg2.evaluate("window.__fp.snapPicture('pic1')")
    check("picture snaps flat onto the wall and faces the room", abs(sn[0] + 19.88) < 0.02 and abs(sn[2] - 90) < 1, sn)
    st_img = pg2.evaluate(f"fetch('api/backgrounds/{up}').then(r => r.status)")
    check("picture image is served", st_img == 200, st_img)
    check("garden objects are kept", pg2.evaluate("window.__fp.layout.floors[1].devices.length") == g + 9)
    pg2.click("#floorPills .pill:last-child"); pg2.wait_for_timeout(400)
    check("whole-house view switches on", pg2.evaluate("window.__fp.houseMode()") is True)
    pg2.click("#floorPills .pill >> nth=1"); pg2.wait_for_timeout(300)
    check("clicking a floor leaves the whole-house view", pg2.evaluate("window.__fp.houseMode()") is False)
    pg2.evaluate("window.__fp.setHouseMode(true)"); pg2.wait_for_timeout(1200)
    pg2.screenshot(path=f"{S}/house.png")
    pg2.evaluate("window.__fp.setHouseMode(false)")
    pg2.wait_for_timeout(1800)
    pg2.screenshot(path=f"{S}/stairs.png")
    pg2.close()
    # --- a user who is neither admin nor editor only gets the read-only live view
    pg3 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "tablet_wz"})
    pg3.goto(BASE + "?debug=1"); pg3.wait_for_timeout(1500)
    cls = pg3.evaluate("document.body.className")
    check("non-editor gets read-only UI", "readonly" in cls and "kiosk" in cls, cls)
    pg4 = b.new_page(viewport={"width": 1280, "height": 800})
    pg4.goto(BASE + "?debug=1&kiosk=1"); pg4.wait_for_timeout(1200)
    pg5 = b.new_page(viewport={"width": 1280, "height": 800})
    pg5.goto(BASE + "?debug=1&kiosk=1&perf=high"); pg5.wait_for_timeout(1200)
    check("low-power mode: on for ?kiosk, ?perf=high overrides", pg4.evaluate("window.__fp.LOW") is True and pg5.evaluate("window.__fp.LOW") is False)
    pg4.close(); pg5.close()
    code = pg3.evaluate("fetch('api/layout', {method:'PUT', headers:{'Content-Type':'application/json'}, body: JSON.stringify({version:1,floors:[]})}).then(r => r.status)")
    check("non-editor cannot save (403)", code == 403, code)
    pg3.close()
    # --- several houses + per-pane window sensors
    pg6 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
    pg6.on("dialog", lambda d: d.accept("Eltern") if d.type == "prompt" else d.accept())
    pg6.goto(BASE + "?debug=1&mode=edit"); pg6.wait_for_timeout(1500)
    h0 = pg6.evaluate("window.__fp.houseId()")
    pg6.evaluate("document.querySelector('#housePanel').open = true")
    0 and print("DBG", pg6.evaluate("[document.body.className, document.querySelector('#housePanel').open, JSON.stringify(document.querySelector('#panel').getBoundingClientRect())]"))
    pg6.click("#houseNew"); pg6.wait_for_timeout(1200)
    hs = api("api/houses")
    check("new house is created and selected", len(hs) == 2 and pg6.evaluate("window.__fp.houseId()") != h0, hs)
    check("new house starts empty", pg6.evaluate("window.__fp.layout.floors.reduce((n, f) => n + f.walls.length, 0)") == 0)
    check("house select is shown with 2 houses", pg6.is_visible("#houseSelect"))
    pg6.evaluate("window.__fp.layout.floors[0].walls.push({id:'wx',a:{x:0,z:0},b:{x:4,z:0},height:2.5,thickness:0.2,openings:[]})")
    pg6.evaluate("window.__fp.layout.floors[0].walls[0].openings.push({id:'wnd3',type:'window',style:'triple',pos:2,width:2.4,height:1.2,sill:0.9,paneEntities:['binary_sensor.a','','binary_sensor.c']})")
    h1 = pg6.evaluate("window.__fp.houseId()")
    pg6.evaluate(f"window.__fp.switchHouse('{h0}')"); pg6.wait_for_timeout(1200)
    check("switching back loads the other house's layout", pg6.evaluate("window.__fp.layout.floors.reduce((n, f) => n + f.walls.length, 0)") > 0)
    kiosk = b.new_page(extra_http_headers={"X-Remote-User-Name": "admin"}); kiosk.goto(BASE + "?debug=1&house=Eltern"); kiosk.wait_for_function("window.__fp && window.__fp.houseId()", timeout=45000)
    check("?house=<name> opens that house", kiosk.evaluate("window.__fp.houseId()") == h1, (kiosk.evaluate("window.__fp.houseId()"), h1))
    kiosk.close()
    pg6.evaluate(f"window.__fp.switchHouse('{h1}')"); pg6.wait_for_timeout(800)
    pg6.click("#houseDelete"); pg6.wait_for_timeout(1000)
    check("house can be deleted again", len(api("api/houses")) == 1)
    pg6.close()
    pg7 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
    pg7.goto(BASE + "?debug=1"); pg7.wait_for_timeout(1500)
    fi = pg7.evaluate("""() => { const f = window.__fp.layout.floors.find(x => x.walls.length); const w = f.walls[0];
      w.openings = w.openings || []; w.openings.push({id:'wnd3', type:'window', style:'triple', pos: 1.0, width: 1.2, height:1.2, sill:0.9, paneEntities:['binary_sensor.p1','','binary_sensor.p3']}); return window.__fp.layout.floors.indexOf(f); }""")
    pg7.click(f"#floorPills .pill >> nth={fi}"); pg7.evaluate("window.__fp.rebuild()"); pg7.wait_for_timeout(500)
    pg7.evaluate("window.__fp.fakeState('binary_sensor.p3', 'on'); window.__fp.fakeState('binary_sensor.p1', 'off')")
    tg = pg7.evaluate("window.__fp.paneTargets('wnd3')")
    check("each pane follows its own sensor", len(tg) == 3 and tg[0] == 0 and tg[1] == 0 and tg[2] < 0, tg)
    pg7.close()
    # --- backup export / import
    pg8 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
    pg8.on("dialog", lambda d: d.accept())
    pg8.goto(BASE + "?debug=1&mode=edit"); pg8.wait_for_timeout(1500)
    bk = pg8.evaluate("fetch('api/backup').then(r => r.json())")
    check("backup contains houses, settings and files", bk["format"] == "floorplan3d-backup" and len(bk["houses"]) >= 1 and "models" in bk, list(bk))
    Path(f"{S}/backup.json").write_text(json.dumps(bk))
    n_walls = pg8.evaluate("window.__fp.layout.floors.reduce((n, f) => n + f.walls.length, 0)")
    pg8.evaluate("window.__fp.layout.floors.forEach(f => { f.walls.length = 0; }); window.__fp.layout.floors[0].name = 'kaputt'")
    pg8.evaluate("fetch('api/layout', {method:'PUT', headers:{'Content-Type':'application/json'}, body: JSON.stringify(window.__fp.layout)})"); pg8.wait_for_timeout(500)
    pg8.evaluate("document.querySelector('#housePanel').open = true")
    pg8.set_input_files("#backupFile", f"{S}/backup.json"); pg8.wait_for_timeout(3000)
    n2 = sum(len(f["walls"]) for f in api("api/layout")["floors"])
    check("backup import restores the layout", n2 == n_walls and n_walls > 0, (n_walls, n2))
    pg8.close()
    # --- lock checkbox in the object list (any item)
    pg9 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
    pg9.goto(BASE + "?debug=1&mode=edit"); pg9.wait_for_timeout(1500)
    fi9 = pg9.evaluate("window.__fp.layout.floors.findIndex(f => f.walls.length && f.devices.length)")
    pg9.click(f"#floorPills .pill >> nth={max(fi9, 0)}"); pg9.wait_for_timeout(600)
    pg9.evaluate("document.querySelectorAll('#objList details').forEach(d => { d.open = true; })"); pg9.wait_for_timeout(200)
    ngrp = pg9.locator("#objList details > summary").count()
    pg9.fill("#objList .objfilter", "zzzz-nothing"); pg9.wait_for_timeout(200)
    nfilt = pg9.locator("#objList details").count()
    pg9.fill("#objList .objfilter", ""); pg9.wait_for_timeout(200)
    pg9.evaluate("document.querySelectorAll('#objList details').forEach(d => { d.open = true; })")
    check("object list is grouped and filterable", ngrp >= 2 and nfilt == 0, (ngrp, nfilt))
    nl = pg9.locator("#objList .objlock").count()
    check("object list has a lock checkbox per item", nl >= 4, nl)
    pg9.locator("#objList details[open] .objlock").first.check(); pg9.wait_for_timeout(300)
    locked = pg9.evaluate("window.__fp.layout.floors.flatMap(f => [...f.rooms, ...f.walls, ...f.devices]).filter(x => x.locked).length")
    check("ticking the box locks the item", locked == 1, locked)
    w0 = pg9.evaluate("document.querySelector('#panel').getBoundingClientRect().width")
    bx = pg9.evaluate("(() => { const r = document.querySelector('#panelResizer').getBoundingClientRect(); return [r.x + r.width / 2, r.y + 200]; })()")
    pg9.mouse.move(bx[0], bx[1]); pg9.mouse.down(); pg9.mouse.move(bx[0] - 150, bx[1], steps=5); pg9.mouse.up(); pg9.wait_for_timeout(300)
    w1 = pg9.evaluate("document.querySelector('#panel').getBoundingClientRect().width")
    check("side panel can be widened by dragging its edge", w1 > w0 + 100, (w0, w1))
    pg9.close()
    # --- Nanoleaf layout editor: click panels together, ONE device with one entity
    pg10 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
    pg10.goto(BASE + "?debug=1&mode=edit"); pg10.wait_for_timeout(1500)
    pg10.evaluate("(() => { const f = window.__fp.layout.floors[0]; f.devices.push({id:'nano1', type:'nanoleaf', x:1, z:1, y:1.4, rot:0, scale:1, name:'Leaves', entity:'light.wohnzimmer', panels:[{s:'sq',x:-0.12,y:0,r:0},{s:'sq',x:0.12,y:0,r:0}]}); window.__fp.rebuild(); window.__fp.editNano('nano1'); })()")
    pg10.wait_for_selector("#nanoCanvas", timeout=10000); pg10.wait_for_timeout(300)
    box = pg10.locator("#nanoCanvas").bounding_box()
    pg10.click("[data-shape=tri]")
    for dx, dy in [(0.0, -0.3), (0.0, 0.3), (0.45, 0.0)]:
        pg10.mouse.click(box["x"] + box["width"] / 2 + dx * box["width"] * 0.35, box["y"] + box["height"] / 2 + dy * box["height"] * 0.6); pg10.wait_for_timeout(100)
    pg10.click("[data-shape=tri2]"); pg10.mouse.click(box["x"] + box["width"] / 2 - 0.3 * box["width"] * 0.35, box["y"] + box["height"] / 2); pg10.wait_for_timeout(100)
    cnt = pg10.inner_text("#nanoCount")
    pg10.click("#nanoOk"); pg10.wait_for_timeout(500)
    np_ = pg10.evaluate("window.__fp.layout.floors[0].devices.find(d => d.id === 'nano1').panels.length")
    check("nanoleaf editor adds snapped panels to one device", np_ >= 5 and pg10.locator("#nanoDialog").count() == 0, (np_, cnt))
    pg10.evaluate("window.__fp.layout.floors[0].devices.find(d => d.id === 'nano1').hideModel = true; window.__fp.rebuild()")
    pg10.click("#modeSwitch button[data-mode=live]"); pg10.wait_for_timeout(500)
    hid = pg10.evaluate("window.__fp.isShown('nano1')")
    pg10.click("#modeSwitch button[data-mode=edit]"); pg10.wait_for_timeout(500)
    shown = pg10.evaluate("window.__fp.isShown('nano1')")
    check("invisible light is hidden in live mode only", hid is False and shown is True, (hid, shown))
    pg10.evaluate("(() => { const f = window.__fp.layout.floors[0]; f.devices.push({id:'tvx', type:'tv_wall', x:3, z:2, y:1.2, rot:0, scale:1, name:'TV', entity:'', ledEntity:'light.wohnzimmer'}, {id:'tvy', type:'tv', x:5, z:2, y:0.5, rot:0, scale:1, name:'TV2', entity:''}); window.__fp.rebuild(); })()")
    pg10.wait_for_timeout(300)
    check("TV with a backlight entity shows its built-in LED frame", pg10.evaluate("window.__fp.ledShown('tvx')") is True and pg10.evaluate("window.__fp.ledShown('tvy')") is False)
    pg10.evaluate("(() => { const f = window.__fp.layout.floors[0]; f.rooms.push({id:'rp1', name:'Presence room', color:'#888', points:[[0,8],[6,8],[6,12],[0,12]]}); f.devices.push({id:'pr1', type:'presence', x:2, z:10, y:0, rot:0, scale:1, name:'Anna', entity:'person.anna'}); window.__fp.rebuild(); })()")
    pg10.click("#modeSwitch button[data-mode=live]"); pg10.wait_for_timeout(600)
    pg10.evaluate("window.__fp.fakeState('person.anna', 'home'); window.__fp.rebuild()"); pg10.wait_for_timeout(300)
    here = pg10.evaluate("window.__fp.isShown('pr1')"); dot = pg10.locator("#roomPills .pill.occupied").count()
    pg10.evaluate("window.__fp.fakeState('person.anna', 'not_home'); window.__fp.rebuild()"); pg10.wait_for_timeout(300)
    away = pg10.evaluate("window.__fp.isShown('pr1')"); dot2 = pg10.locator("#roomPills .pill.occupied").count()
    check("presence: person shows with a dot on the room while home, hides when away", here is True and dot == 1 and away is False and dot2 == 0, (here, dot, away, dot2))
    pg10.close()
    # --- LED ring: placed in a room it runs all around under the ceiling, every section has its own light
    pg12 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
    pg12.on("pageerror", lambda e: errors.append("PAGEERROR " + str(e)))
    pg12.goto(BASE + "?debug=1&mode=edit"); pg12.wait_for_timeout(1500)
    pg12.evaluate("(() => { const f = window.__fp.layout.floors[0]; f.rooms.push({id:'rr1', name:'Ring room', color:'#888', points:[[20,0],[24,0],[24,3],[20,3]]}); window.__fp.rebuild(); })()")
    pg12.click("#view2d"); pg12.wait_for_timeout(500)
    pg12.click("button[data-tool=device]"); pg12.select_option("#entitySelect", "")
    pg12.fill("#paletteSearch", "ledring"); pg12.wait_for_timeout(200)
    pg12.click("#paletteGrid button.dev >> nth=0")
    pg12.evaluate("window.__fp.plan().fit && window.__fp.plan().fit()"); pg12.wait_for_timeout(300)
    c = pg12.evaluate("window.__fp.plan().toClient(22,1.5)"); pg12.mouse.click(*c); pg12.wait_for_timeout(400)
    ring = pg12.evaluate("window.__fp.layout.floors[0].devices.find(d => d.type === 'ledring')")
    wh = pg12.evaluate("fetch('api/settings').then(r => r.json()).then(s => s.wallHeight)")
    xs = sorted(round(ring["x"] + p[0], 3) for p in ring["pts"]) if ring else []
    check("LED ring placed in a room runs around it under the ceiling", ring and len(ring["pts"]) == 4 and len(ring["segs"]) == 4 and ring["closed"] is True
          and xs[0] == 20.15 and xs[-1] == 23.85 and abs(ring["y"] - (wh - 0.1)) < 0.01 and ring.get("room") == "rr1", ring)
    pg12.click("button[data-tool=select]")
    c = pg12.evaluate("window.__fp.plan().toClient(22,1.5)"); pg12.mouse.click(*c); pg12.wait_for_timeout(300)
    mid_sel = pg12.inner_text("#propsTitle")
    c = pg12.evaluate("window.__fp.plan().toClient(22,0.15)"); pg12.mouse.click(*c); pg12.wait_for_timeout(300)
    check("2D: inside the ring the room is picked, on the line the ring", pg12.is_visible("#ringFit") and mid_sel != pg12.inner_text("#propsTitle"), mid_sel)
    check("ring properties list one light per section", pg12.locator("#propsBody .entPicker").count() == 5)
    rid = ring["id"]
    # state set and read in one step: the regular poll would otherwise bring back the mock's real state
    g1 = pg12.evaluate(f"(() => {{ const d = window.__fp.layout.floors[0].devices.find(v => v.id === '{rid}'); d.segs[0] = {{entity: 'light.wohnzimmer'}}; window.__fp.fakeState('light.wohnzimmer', 'on'); window.__fp.rebuild(); return window.__fp.ringGlow('{rid}'); }})()")
    check("only the section with a lit light glows", g1 == [True, False, False, False], g1)
    g2 = pg12.evaluate(f"(() => {{ window.__fp.layout.floors[0].devices.find(v => v.id === '{rid}').entity = 'light.wohnzimmer'; window.__fp.fakeState('light.wohnzimmer', 'on'); window.__fp.rebuild(); return window.__fp.ringGlow('{rid}'); }})()")
    check("sections without own light follow the ring's main entity", g2 == [True, True, True, True], g2)
    pg12.click("#ringClosed"); pg12.wait_for_timeout(300)
    opened = len(pg12.evaluate(f"window.__fp.layout.floors[0].devices.find(v => v.id === '{rid}').segs"))
    pg12.click("#ringClosed"); pg12.wait_for_timeout(300)
    closed = pg12.evaluate(f"window.__fp.layout.floors[0].devices.find(v => v.id === '{rid}')")
    check("ring can be opened (one section less) and closed again", opened == 3 and len(closed["segs"]) == 4 and closed["segs"][0] == {"entity": "light.wohnzimmer"}, (opened, closed["segs"]))
    pg12.click("#view3d"); pg12.wait_for_timeout(300)
    pg12.click("#modeSwitch button[data-mode=live]"); pg12.wait_for_timeout(600)
    pg12.evaluate("window.__fp.topDown()"); pg12.wait_for_timeout(300)
    sp = pg12.evaluate(f"window.__fp.ringSegScreen('{rid}', 2)")
    hit = pg12.evaluate(f"window.__fp.pickAt({sp['x']}, {sp['y']})") if sp else None
    if sp: pg12.mouse.click(sp["x"], sp["y"]); pg12.wait_for_timeout(400)
    txt = pg12.inner_text("#livePopup") if pg12.is_visible("#livePopup") else ""
    check("live: tapping a section opens it with the section buttons", hit and hit.get("seg") == 2 and pg12.locator("#livePopup .ringSegs button.sel").inner_text() == "3" and pg12.locator("#livePopup .ringSegs button").count() == 4, (hit, txt[:120]))
    pg12.close()
    pg11 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
    pg11.goto(BASE + "?debug=1&mode=edit"); pg11.wait_for_timeout(1500)
    nh = pg11.evaluate("fetch('api/houses').then(r => r.json()).then(h => h.length)")
    pg11.evaluate("document.querySelector('#housePanel').open = true")
    pg11.click("#importOpen"); pg11.wait_for_selector("#importDialog[open]", timeout=5000)
    check("import: run is disabled before a check", pg11.locator("#importRun").is_disabled())
    pg11.click("#importExHouse"); pg11.wait_for_timeout(500)
    pg11.click("#importCheck"); pg11.wait_for_selector("#importResult .imp-ok", timeout=5000)
    pg11.screenshot(path=os.path.join(os.path.dirname(__file__), "import.png"))
    check("import: check succeeds and enables the import", pg11.locator("#importRun").is_enabled())
    pg11.fill("#importText", "{kaputt"); pg11.click("#importCheck"); pg11.wait_for_selector("#importResult .imp-errors", timeout=5000)
    check("import: broken JSON shows an error and keeps run disabled", pg11.locator("#importRun").is_disabled())
    pg11.click("#importExFlat"); pg11.wait_for_timeout(300); pg11.click("#importCheck"); pg11.wait_for_selector("#importResult .imp-ok", timeout=5000)
    pg11.click("#importRun"); pg11.wait_for_timeout(2000)
    nh2 = pg11.evaluate("fetch('api/houses').then(r => r.json()).then(h => h.length)")
    fl = pg11.evaluate("window.__fp.layout.floors.length")
    check("import: creates a new house and switches to it", nh2 == nh + 1 and fl == 1 and pg11.locator("#importDialog[open]").count() == 0, (nh, nh2, fl))
    pg11.close()
    pg12 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
    shots = os.path.join(os.path.dirname(__file__), "lang")
    os.makedirs(shots, exist_ok=True)
    for code, word in (("fr", "Mur"), ("es", "Pared"), ("it", "Parete"), ("nl", "Muur"), ("pl", "Ściana")):
        pg12.request.put(BASE + "api/settings", data=json.dumps({"language": code}), headers={"Content-Type": "application/json"})
        pg12.goto(BASE + "?debug=1&mode=edit"); pg12.wait_for_timeout(1200)
        txt = pg12.inner_text("#toolbar")
        pg12.screenshot(path=os.path.join(shots, code + ".png"))
        check("UI switches to " + code, word in txt, txt[:200])
    pg12.request.put(BASE + "api/settings", data=json.dumps({"language": "de"}), headers={"Content-Type": "application/json"})
    pg12.close()
    b.close()

bad = [e for e in errors if "favicon" not in e]

check("no console errors", not bad, bad)
print("\n%d/%d passed" % (sum(ok for _, ok in results), len(results)))
sys.exit(0 if all(ok for _, ok in results) else 1)
