"""Users and rights: read-only tablet view, the users tab and its file, presets per user (#250), labels of the floors below (#249), arrow keys and the floors switch (#98, #99).
"""
# --- a user who is neither admin nor editor only gets the read-only live view
pg3 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "tablet_wz"})
pg3.goto(BASE + "?debug=1"); pg3.wait_for_timeout(1500)
cls = pg3.evaluate("document.body.className")
check("non-editor gets read-only UI", "readonly" in cls and "kiosk" in cls, cls)
pg4 = b.new_page(viewport={"width": 1280, "height": 800})
pg4.goto(BASE + "?debug=1&kiosk=1"); pg4.wait_for_timeout(1200)
pg5 = b.new_page(viewport={"width": 1280, "height": 800})
pg5.goto(BASE + "?debug=1&kiosk=1&perf=high"); pg5.wait_for_timeout(1200)
check("low-power mode: on for ?kiosk, ?perf=high overrides", pg4.evaluate("window.__fp.LOW") is True and pg5.evaluate("window.__fp.LOW") is False)
pg4.close(); pg5.close()
code = pg3.evaluate("fetch('api/layout', {method:'PUT', headers:{'Content-Type':'application/json'}, body: JSON.stringify({version:1,floors:[]})}).then(r => r.status)")
check("non-editor cannot save (403)", code == 403, code)
check("users tab: hidden for a read-only user", not pg3.locator("#usersBtn").is_visible())
pg3.close()
# --- users & tablets: an own tab in the top bar (not in the gear), saved into a file of the config folder, sync button
pgU = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgU.goto(BASE + "?debug=1&mode=edit"); pgU.wait_for_timeout(1500)
check("users tab: visible in the top bar for admins", pgU.locator("#usersBtn").is_visible())
pgU.click("#settingsBtn"); pgU.wait_for_timeout(200)
check("users & tablets are no longer inside the gear dialog", pgU.locator("#settingsDialog #tabletRows").count() == 0)
pgU.keyboard.press("Escape"); pgU.click("#usersBtn"); pgU.wait_for_timeout(300)
pgU.click("#addTablet"); pgU.fill("#tabletRows .tablet input", "tablet_flur"); pgU.press("#tabletRows .tablet input", "Tab"); pgU.wait_for_timeout(700)
uf = pgU.evaluate("fetch('api/users-file').then(r => r.json())"); uv = api("api/settings")["userViews"]
check("users tab: a tablet is saved and written to the file", "tablet_flur" in uv and uf.get("inSync") is True and uf.get("fileUsers", 0) >= 1, (uv, uf))
pgU.click("#usersSave"); pgU.wait_for_timeout(600)
check("users tab: the save button creates the file", pgU.evaluate("fetch('api/users-file').then(r => r.json())")["exists"] is True)
pgU.click("#usersSync"); pgU.wait_for_timeout(600)
check("users tab: sync loads the file back", "tablet_flur" in pgU.evaluate("window.__fp ? [...document.querySelectorAll('#tabletRows input[data-role=user]')].map(i => i.value) : []") and pgU.inner_text("#usersFileStatus") != "")
pgU.close()
# --- #100: saving from the users dialog must not reset the design (the settings form was only filled after opening the gear)
pgV = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgV.goto(BASE + "?mode=edit"); pgV.wait_for_timeout(1200)
pgV.evaluate("fetch('api/settings').then(r => r.json().then(s => fetch('api/settings', {method: 'PUT', headers: {'Content-Type': 'application/json', 'If-Match': r.headers.get('ETag')}, body: JSON.stringify({...s, theme: 'light'})})))"); pgV.wait_for_timeout(500)
pgV.goto(BASE + "?mode=edit"); pgV.wait_for_timeout(1200)
pgV.click("#usersBtn"); pgV.wait_for_timeout(400); pgV.click("#usersSave"); pgV.wait_for_timeout(800)
check("users dialog: saving the file keeps the design", api("api/settings")["theme"] == "light", api("api/settings")["theme"])
pgV.evaluate("fetch('api/settings').then(r => r.json().then(s => fetch('api/settings', {method: 'PUT', headers: {'Content-Type': 'application/json', 'If-Match': r.headers.get('ETag')}, body: JSON.stringify({...s, theme: 'holo'})})))"); pgV.wait_for_timeout(400)
pgV.close()
# --- view presets per user / tablet (#250): start values only in that user's browser, never saved as everybody's settings
glob = api_admin("api/settings")
set_setting("userPresets", {"tablet_pre": {"seeThrough": True, "belowLabels": False, "labelMode": "all"}, "admin": {"labelMode": "none"}})
pgP = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "tablet_pre"})
pgP.goto(BASE + "?debug=1"); pgP.wait_for_timeout(1500)
sp = pgP.evaluate("(() => { const s = window.__fp.settings(); return [s.seeThrough, s.belowLabels, s.labelMode, s.cutaway]; })()")
check("presets (#250): a tablet starts with its own look", sp == [True, False, "all", glob["cutaway"]], sp)
pgP.close()
pgA = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgA.goto(BASE + "?debug=1&mode=edit"); pgA.wait_for_timeout(1500)
check("presets (#250): an admin with a preset sees it too", pgA.evaluate("window.__fp.settings().labelMode") == "none")
view_menu(pgA); pgA.click("#autoToggle"); pgA.wait_for_timeout(800)
now = api_admin("api/settings")
check("presets (#250): saving another setting keeps everybody's value of the preset field", now["labelMode"] == glob["labelMode"] and now["cutaway"] != glob["cutaway"] and pgA.evaluate("window.__fp.settings().labelMode") == "none", (now["labelMode"], now["cutaway"]))
view_menu(pgA); pgA.click("#autoToggle"); pgA.wait_for_timeout(800)
pgA.keyboard.press("Escape"); pgA.click("#usersBtn"); pgA.wait_for_timeout(500)
ri = pgA.evaluate("[...document.querySelectorAll('#tabletRows .tablet')].findIndex(r => r.querySelector('[data-role=user]').value === 'tablet_pre')")
row = pgA.locator("#tabletRows .tablet").nth(max(ri, 0))
check("presets (#250): the users dialog shows a preset button with the count", ri >= 0 and row.locator(".presetBtn.active").count() == 1 and row.locator(".presetBtn").inner_text() == "⚙ 3", row.locator(".presetBtn").inner_text() if row.count() else "no row")
row.locator(".presetBtn").click(); pgA.wait_for_timeout(200)
row.locator("select[data-preset=belowMode]").select_option("stacked"); pgA.wait_for_timeout(800)
check("presets (#250): a dropdown in the box is saved for that user", api_admin("api/settings")["userPresets"].get("tablet_pre", {}).get("belowMode") == "stacked", api_admin("api/settings")["userPresets"])
pgA.close()
set_setting("userPresets", {})
# --- the labels of the floors below can be left out while one floor is shown (#249)
pgL = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgL.goto(BASE + "?debug=1&mode=edit"); pgL.wait_for_timeout(1500)
lay_saved = api_admin("api/layout")
pgL.evaluate("""() => { const fp = window.__fp, L = fp.layout;
  L.floors[0].devices.push({ id: 'blS', type: 'sensor', x: 1, z: 1, y: 1, rot: 0, scale: 1, name: 'T', entity: 'sensor.bl_test' });
  L.floors.push({ id: 'blF', name: 'Oben', walls: [], rooms: [], devices: [] });
  window.__fp.fakeState('sensor.bl_test', '21.5', '°C'); fp.switchFloor(L.floors.length - 1); fp.rebuild(); fp.applyStates(); }""")
pgL.wait_for_timeout(500)
shown = pgL.evaluate("window.__fp.badge('blS')")
check("value labels are dark pills (they were plain text once after a code split)", pgL.evaluate("window.__fp.badgePill('blS')") is True)
view_menu(pgL); pgL.click("#belowLabelsToggle"); pgL.wait_for_timeout(800)
hidden = pgL.evaluate("window.__fp.badge('blS')")
check("labels below (#249): the switch leaves out the labels of the floors below", shown is not None and hidden is None and api_admin("api/settings")["belowLabels"] is False and not pgL.locator("#belowLabelsToggle.active").count(), (shown, hidden))
pgL.evaluate("window.__fp.setHouseMode(true)"); pgL.wait_for_timeout(600)
check("labels below (#249): the whole house still shows every label", pgL.evaluate("window.__fp.badge('blS')") is not None)
pgL.evaluate("window.__fp.setHouseMode(false)"); pgL.wait_for_timeout(400)
view_menu(pgL); pgL.click("#belowLabelsToggle"); pgL.wait_for_timeout(800)
check("labels below (#249): switched on again they are back", pgL.evaluate("window.__fp.badge('blS')") is not None and api_admin("api/settings")["belowLabels"] is True)
pgL.wait_for_timeout(2500)
pgL.evaluate("(l) => fetch('api/layout', {method:'PUT', headers:{'Content-Type':'application/json'}, body: JSON.stringify(l)})", lay_saved); pgL.wait_for_timeout(400)
pgL.close()
# --- #98 arrow keys change the floor when nothing is selected, #99 the plan-floors switch is hidden in pure 3D
pgA = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgA.goto(BASE + "?debug=1&mode=edit"); pgA.wait_for_timeout(1500)
pgA.click("#view3d"); pgA.wait_for_timeout(200)
pgA.click("#viewMenuBtn"); pgA.wait_for_timeout(100)
check("view menu: floors-in-plan switch is hidden in pure 3D", not pgA.locator("#planFloorsToggle").is_visible())
pgA.click("#view2d"); pgA.wait_for_timeout(200)
check("plan floors chip is shown in 2D", pgA.locator("#planFloorsChip").is_visible())
pgA.click("#view3d"); pgA.wait_for_timeout(200)
nf = pgA.evaluate("window.__fp.layout.floors.length")
if nf >= 2:
    pgA.keyboard.press("Escape"); pgA.keyboard.press("ArrowDown"); pgA.wait_for_timeout(200)
    a0 = pgA.evaluate("window.__fp.floorIdx()")
    pgA.keyboard.press("ArrowUp"); pgA.wait_for_timeout(200)
    a1 = pgA.evaluate("window.__fp.floorIdx()")
    check("arrow keys change the floor", isinstance(a0, int) and isinstance(a1, int) and a0 != a1, (a0, a1))
pgA.close()
