"""Tool bar, placing and the side menus: customisable tool bar, splitting walls, placed devices stay selected, backups (#321), start view (#315), the version pill.
"""
# --- customisable tool bar: dormer button, folded "More" menu, hide / order stored per browser
pgT = b.new_page(viewport={"width": 1500, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgT.goto(BASE + "?debug=1&mode=edit"); pgT.wait_for_timeout(1500)
check("tool bar: dormer button is in the bar", pgT.locator("#dormerBtn").is_visible())
check("tool bar: house import is folded into More by default", pgT.locator("#toolsMoreBtn").is_visible() and not pgT.locator("#importBtn").is_visible())
pgT.click("#toolsMoreBtn"); pgT.wait_for_timeout(150)
check("tool bar: the More menu shows the import button", pgT.locator("#importBtn").is_visible())
pgT.keyboard.press("Escape"); pgT.wait_for_timeout(100)
pgT.click("#toolsEditBtn"); pgT.wait_for_timeout(200)
pgT.locator("#toolsList .tbRow").nth(1).locator("input").first.uncheck(); pgT.wait_for_timeout(100)
check("tool bar: a tool can be hidden", not pgT.locator("[data-tool=wall]").is_visible())
check("tool bar: the selection tool can not be hidden", pgT.locator("#toolsList .tbRow").first.locator("input").first.is_disabled())
pgT.keyboard.press("Escape"); pgT.reload(); pgT.wait_for_timeout(1500)
check("tool bar: the choice survives a reload", not pgT.locator("[data-tool=wall]").is_visible())
pgT.click("#toolsEditBtn"); pgT.wait_for_timeout(200); pgT.click("#toolsReset"); pgT.wait_for_timeout(100)
check("tool bar: reset shows every tool again", pgT.locator("[data-tool=wall]").is_visible())
pgT.keyboard.press("Escape")
pgT.on("dialog", lambda d: d.accept("Dach") if d.type == "prompt" else d.accept())
pgT.click("#dormerBtn"); pgT.wait_for_timeout(900)
check("tool bar: the dormer button opens the dormer section of the roof floor", pgT.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].kind") == "roof" and pgT.locator("#dormerHead").count() == 1)
pgT.close()
# --- double click on a wall in the plan adds a corner (the wall becomes two), undo takes it back
pgW = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgW.goto(BASE + "?debug=1&mode=edit"); pgW.wait_for_timeout(1500)
pgW.click("#view2d"); pgW.wait_for_timeout(500)
pgW.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].walls.push({id: 'wsplit', a: [30, 30], b: [34, 30], thickness: 0.2, height: 2.6, openings: []}); window.__fp.rebuild()"); pgW.wait_for_timeout(300)
pgW.click("#fitBtn"); pgW.wait_for_timeout(400)
n0 = pgW.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].walls.length")
px, py = pgW.evaluate("window.__fp.plan().toClient(32, 30)")
pgW.mouse.dblclick(px, py + 6); pgW.wait_for_timeout(300)           # a few pixels beside the line still counts as the wall
two = pgW.evaluate("(() => { const w = window.__fp.layout.floors[window.__fp.floorIdx()].walls.filter((q) => q.a[1] === 30 && q.b[1] === 30); return [window.__fp.layout.floors[window.__fp.floorIdx()].walls.length, w.length, w.length === 2 && w[0].b[0] === w[1].a[0] && w[0].b[0] > 30.2 && w[0].b[0] < 33.8, w.length === 2 && w[0].a[0] === 30 && w[1].b[0] === 34]; })()")
check("plan: double click on a wall splits it in two at that point", two[0] == n0 + 1 and two[1] == 2 and two[2] and two[3], (n0, two))
pgW.keyboard.press("Control+z"); pgW.wait_for_timeout(300)
check("plan: undo takes the new corner back", pgW.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].walls.length") == n0)
pgW.close()
# --- a placed device stays selected (movable at once), the next click on empty space deselects it and placing goes on
set_setting("placeSelect", True)
pgD = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgD.goto(BASE + "?debug=1&mode=edit"); pgD.wait_for_timeout(1500)
pgD.click("#view2d"); pgD.wait_for_timeout(500)
pgD.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].walls.push({id: 'wfar', a: [30, 30], b: [34, 30], thickness: 0.2, height: 2.6, openings: []}); window.__fp.rebuild()")   # makes the plan reach an empty area
pgD.click("#fitBtn"); pgD.wait_for_timeout(400)
pgD.click("[data-tool=device]"); pgD.wait_for_timeout(200)
nd = lambda: pgD.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].devices.length")
d0 = nd()
px, py = pgD.evaluate("window.__fp.plan().toClient(31, 27)")
pgD.mouse.click(px, py); pgD.wait_for_timeout(300)
check("place: a device is placed", nd() == d0 + 1, (d0, nd()))
check("place: the placed device is selected and the Select tool is active", pgD.evaluate("document.body.dataset.tool") == "select")
px2, py2 = pgD.evaluate("window.__fp.plan().toClient(33, 27)")
pgD.mouse.click(px2, py2); pgD.wait_for_timeout(300)
check("place: the next click on empty space only deselects (no second device)", nd() == d0 + 1 and pgD.evaluate("document.body.dataset.tool") == "device", (d0, nd()))
pgD.mouse.click(px2, py2); pgD.wait_for_timeout(300)
check("place: the click after that places the next device", nd() == d0 + 2, (d0, nd()))
pgD.close()
set_setting("placeSelect", False)
# --- automatic backups: 🗄️ backup dialog in the top bar (#321), back up now, check, settings are kept; toggling Auto without the gear keeps the design
pgB = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgB.goto(BASE + "?debug=1&mode=edit"); pgB.wait_for_timeout(1500)
check("backups (#321): the side panel no longer holds the backup", pgB.locator("#housePanel #autoBackup").count() == 0)
pgB.click("#backupBtn"); pgB.wait_for_selector("#backupDialog[open]", timeout=5000); pgB.wait_for_timeout(800)
check("backups: the automatic backup section is shown", pgB.locator("#autoBackup").is_visible())
check("security (#317): the recorded days are listed in the backup dialog", pgB.locator("#tlSetDays .abRow, #tlSetDays p").count() >= 1, pgB.inner_text("#tlSetDays"))
pgB.fill("#setTimelineKeep", "9"); pgB.press("#setTimelineKeep", "Tab"); pgB.wait_for_timeout(800)
check("security: 'days to keep' is stored", api("api/settings")["timelineKeepDays"] == 9.0, api("api/settings")["timelineKeepDays"])
pgB.click("#abNow"); pgB.wait_for_timeout(1200)
items = api_admin("api/backups")["items"]
check("backups: 'back up now' writes a file into the backups folder", len(items) == 1 and items[0]["kind"] == "manual", items)
check("backups: the list shows it", pgB.locator("#abList .abRow").count() == 1)
pgB.click("#abTest"); pgB.wait_for_timeout(1000)
check("backups: checking the newest backup reports it as fine", "houses" in pgB.inner_text("#abStatus") or "Häuser" in pgB.inner_text("#abStatus"), pgB.inner_text("#abStatus"))
pgB.check("#setAutoBackup"); pgB.fill("#setBackupEvery", "12"); pgB.press("#setBackupEvery", "Tab"); pgB.wait_for_timeout(800)
st = api("api/settings")
check("backups: the schedule settings are stored", st["autoBackup"] is True and st["backupEveryHours"] == 12.0, (st["autoBackup"], st["backupEveryHours"]))
pgB.close()
pgC = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgC.goto(BASE + "?mode=edit"); pgC.wait_for_timeout(1500)
theme0 = api("api/settings")["theme"]
pgC.click("#viewMenuBtn"); pgC.click("#autoToggle"); pgC.wait_for_timeout(800)
st = api("api/settings")
check("settings: toggling Auto without opening the gear keeps all other settings", st["theme"] == theme0 and st["autoBackup"] is True and st["backupEveryHours"] == 12.0, (st["theme"], theme0, st["autoBackup"]))
pgC.click("#viewMenuBtn") if pgC.locator("#viewMenu").is_visible() else None
pgC.evaluate("fetch('api/settings').then(r => r.json().then(s => fetch('api/settings', {method: 'PUT', headers: {'Content-Type': 'application/json', 'If-Match': r.headers.get('ETag')}, body: JSON.stringify({...s, autoBackup: false})})))"); pgC.wait_for_timeout(400)
pgC.close()
# --- start view (#315): take the view shown now in the settings, a new page opens with it, "Automatic" takes it back
pgS = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgS.goto(BASE + "?debug=1&mode=edit"); pgS.wait_for_timeout(1500)
pgS.evaluate("window.__fp.setHouseMode(true)"); pgS.wait_for_timeout(300)
pgS.evaluate("window.__fp.camAt(30, 25, 20, 1, 2)"); pgS.wait_for_timeout(300)
camS = pgS.evaluate("window.__fp.cam()")
pgS.click("#settingsBtn"); pgS.click("#svTake"); pgS.wait_for_timeout(800)
sv = api("api/settings")["startViews"].get("*")
check("start view (#315): 'use current view' stores the whole house and the camera", bool(sv) and sv["whole"] is True and abs(sv["cam"][0] - 30) < 0.01, sv)
check("start view: the settings show it as saved", "Ganzes Haus" in pgS.inner_text("#svState") or "Whole house" in pgS.inner_text("#svState"), pgS.inner_text("#svState"))
pgS.close()
pgS = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgS.goto(BASE + "?debug=1&mode=edit"); pgS.wait_for_timeout(2000)
camN = pgS.evaluate("window.__fp.cam()")
check("start view: a new page opens with it (whole house, same camera)", pgS.evaluate("window.__fp.houseMode()") is True and max(abs(a - c) for a, c in zip(camS, camN)) < 0.05, (camS, camN))
pgS.click("#settingsBtn"); pgS.click("#svAuto"); pgS.wait_for_timeout(800)
check("start view: 'Automatic' removes it", "*" not in api("api/settings")["startViews"], api("api/settings")["startViews"])
pgS.close()
# --- version pill: version and checksum in the top bar, green when add-on files and browser files match the manifest
pgV2 = b.new_page(viewport={"width": 1500, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgV2.goto(BASE + "?mode=edit"); pgV2.wait_for_timeout(2500)
ver = api("api/version")
check("version: the add-on knows its manifest and its files match", ver["known"] and ver["server"]["ok"], ver.get("server"))
check("version: the pill shows version and short checksum", ver["version"] in pgV2.inner_text("#versionPill") and ver["short"] in pgV2.inner_text("#versionPill"), pgV2.inner_text("#versionPill"))
check("version: the pill is green when everything matches", "ver-ok" in (pgV2.get_attribute("#versionPill", "class") or ""), pgV2.get_attribute("#versionPill", "class"))
pgV2.click("#versionPill"); pgV2.wait_for_timeout(300)
check("version: the dialog lists the add-on and browser check", pgV2.locator("#versionBody .verLine.ok").count() >= 2)
pgV2.click("#versionCheck"); pgV2.wait_for_timeout(2500)
check("version: the GitHub comparison answers (also when GitHub is not reachable)", "GitHub" in pgV2.inner_text("#versionBody"))
pgV2.close()
# --- version pill without a secure context (plain http): the checksums are calculated without crypto.subtle (#144) and a newer version on GitHub turns the pill blue (#140)
pgV3 = b.new_page(viewport={"width": 1500, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgV3.add_init_script("Object.defineProperty(window.crypto, 'subtle', {get() { return undefined; }})")
pgV3.route("**/api/version/remote", lambda r: r.fulfill(status=200, content_type="application/json", body='{"state": "behind", "version": "99.0.0", "short": "abcdef0"}'))
pgV3.goto(BASE + "?mode=edit"); pgV3.wait_for_timeout(3500)
check("version: the test page really has no crypto.subtle", pgV3.evaluate("window.crypto.subtle") is None)
pgV3.click("#versionPill"); pgV3.wait_for_timeout(300)
check("version: no secure context, no 'not possible' hint, browser files match", "not possible" not in pgV3.inner_text("#versionBody") and "exactly these files" in pgV3.inner_text("#versionBody"), pgV3.inner_text("#versionBody"))
pgV3.keyboard.press("Escape"); pgV3.wait_for_timeout(200)
check("version: a newer version on GitHub turns the pill blue", "ver-new" in (pgV3.get_attribute("#versionPill", "class") or "") and "99.0.0" in pgV3.inner_text("#versionPill"), pgV3.inner_text("#versionPill"))
pgV3.close()
