"""Houses: a wall beside a door, opening palette, users dialog by house, several houses, window panes, roller shutters (#331), backup export / import, the lock box.
"""
# --- double click on a wall next to a door of a neighbouring wall: the door's generous hit area must not take it away
pgN = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgN.goto(BASE + "?debug=1&mode=edit"); pgN.wait_for_timeout(1500)
pgN.click("#view2d"); pgN.wait_for_timeout(500)
pgN.evaluate("(() => { const w = window.__fp.layout.floors[window.__fp.floorIdx()].walls; w.push({id: 'tA', a: [30, 30], b: [36, 30], thickness: 0.2, height: 2.6, openings: []}, {id: 'tB', a: [33, 30], b: [33, 34], thickness: 0.2, height: 2.6, openings: [{id: 'tDoor', type: 'door', width: 0.9, height: 2.05, sill: 0, pos: 0.7}]}); window.__fp.rebuild(); })()")
pgN.click("#fitBtn"); pgN.wait_for_timeout(400)
cnt = lambda: pgN.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].walls.length")
n0 = cnt(); hit = None
for off in (0.25, 0.3, 0.35, 0.4, 0.45, 0.5, 0.6, 0.7, 0.8):          # beside the door, on wall tA, until the old pick says "opening"
    kind = pgN.evaluate("([x, z]) => window.__fp.plan().pickAt(x, z)?.kind", [33 + off, 30])
    if kind == "opening":
        hit = off; break
check("plan: a spot beside a neighbouring door exists where the plain pick says opening", hit is not None)
if hit is not None:
    px, py = pgN.evaluate("([x, z]) => window.__fp.plan().toClient(x, z)", [33 + hit, 30])
    pgN.mouse.dblclick(px, py); pgN.wait_for_timeout(400)
    check("plan: double click there still splits the wall (a door beside it does not win)", cnt() == n0 + 1, (n0, cnt()))
# the wall's properties split it at an exact distance or into equal parts (wallsplit.js)
pgN.evaluate("(() => { window.__fp.layout.floors[window.__fp.floorIdx()].walls.push({id: 'tS', a: [40, 40], b: [50, 40], thickness: 0.2, height: 2.6, openings: []}); window.__fp.rebuild(); })()")
pgN.click("#fitBtn"); pgN.wait_for_timeout(400)
pgN.mouse.click(*pgN.evaluate("([x, z]) => window.__fp.plan().toClient(x, z)", [45, 40])); pgN.wait_for_timeout(400)
tS = lambda: pgN.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].walls.filter(w => w.a[1] === 40 && w.b[1] === 40 && w.a[0] >= 40).map(w => [w.a[0], w.b[0]]).sort((p, q) => p[0] - q[0])")
ft = pgN.evaluate("window.__fp.settings().units") == "imperial"           # the field shows the current unit (feet here)
pgN.fill("#wallSplitAt", f"{0.3 * 3.28084:.5f}" if ft else "0.3"); pgN.click("#wallSplitBtn"); pgN.wait_for_timeout(300)
check("wall split: a corner at an exact distance (30 cm from the start)", tS() == [[40, 40.3], [40.3, 50]], tS())
pgN.select_option("#wallParts", "3"); pgN.click("#wallPartsBtn"); pgN.wait_for_timeout(300)
check("wall split: the selected piece in 3 equal parts", tS() == [[40, 40.1], [40.1, 40.2], [40.2, 40.3], [40.3, 50]], tS())
pgN.evaluate("(() => { const f = window.__fp.layout.floors[window.__fp.floorIdx()]; f.walls = f.walls.filter(w => !(w.a[1] === 40 && w.b[1] === 40 && w.a[0] >= 40)); window.__fp.rebuild(); })()")   # leave the house as it was for the later checks
pgN.close()
# --- opening palette is grouped (doors, passages, windows)
pgP = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgP.goto(BASE + "?mode=edit"); pgP.wait_for_timeout(1200)
pgP.click("[data-tool=opening]"); pgP.wait_for_timeout(200)
check("opening palette: three groups with headings", pgP.locator("#openingPalette .opGroup").count() == 3 and pgP.locator("#openingPalette button[data-opening]").count() == 14)
pgP.close()
# --- users dialog: rooms grouped by house
pgG = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgG.goto(BASE + "?debug=1&mode=edit"); pgG.wait_for_timeout(1500)
ex = json.load(open(os.path.join(S, "..", "..", "docs", "examples", "house.json")))
pgG.evaluate("(ex) => fetch('api/import?name=Gruppen%20Haus', {method: 'POST', headers: {'Content-Type': 'application/json'}, body: JSON.stringify(ex)})", ex); pgG.wait_for_timeout(500)
pgG.reload(); pgG.wait_for_timeout(1500)
pgG.click("#usersBtn"); pgG.wait_for_timeout(1200); pgG.click("#addTablet"); pgG.wait_for_timeout(200)
groups = pgG.evaluate("[...document.querySelectorAll('#tabletRows .tablet [data-role=room] optgroup')].map(g => g.label)")
check("users dialog: room list is grouped by house", "Gruppen Haus" in groups and len(groups) >= 1, groups)
check("users dialog: a room shows its floor", pgG.evaluate("[...document.querySelectorAll('#tabletRows .tablet [data-role=room] option')].some(o => o.textContent.includes(' · '))"))
pgG.evaluate("fetch('api/houses').then(r => r.json()).then(l => Promise.all(l.filter(h => h.name === 'Gruppen Haus').map(h => fetch('api/houses/' + h.id, {method: 'DELETE'}))))"); pgG.wait_for_timeout(300)
pgG.close()
# --- several houses + per-pane window sensors
pg6 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pg6.on("dialog", lambda d: d.accept("Eltern") if d.type == "prompt" else d.accept())
pg6.goto(BASE + "?debug=1&mode=edit"); pg6.wait_for_timeout(1500)
h0 = pg6.evaluate("window.__fp.houseId()")
pg6.evaluate("document.querySelector('#housePanel').open = true")
0 and print("DBG", pg6.evaluate("[document.body.className, document.querySelector('#housePanel').open, JSON.stringify(document.querySelector('#panel').getBoundingClientRect())]"))
pg6.click("#houseNew"); pg6.wait_for_timeout(1200)
hs = api("api/houses")
check("new house is created and selected", len(hs) == 2 and pg6.evaluate("window.__fp.houseId()") != h0, hs)
check("new house starts empty", pg6.evaluate("window.__fp.layout.floors.reduce((n, f) => n + f.walls.length, 0)") == 0)
check("house select is shown with 2 houses", pg6.is_visible("#houseSelect"))
pg6.evaluate("window.__fp.layout.floors[0].walls.push({id:'wx',a:{x:0,z:0},b:{x:4,z:0},height:2.5,thickness:0.2,openings:[]})")
pg6.evaluate("window.__fp.layout.floors[0].walls[0].openings.push({id:'wnd3',type:'window',style:'triple',pos:2,width:2.4,height:1.2,sill:0.9,paneEntities:['binary_sensor.a','','binary_sensor.c']})")
h1 = pg6.evaluate("window.__fp.houseId()")
pg6.evaluate(f"window.__fp.switchHouse('{h0}')"); pg6.wait_for_timeout(1200)
check("switching back loads the other house's layout", pg6.evaluate("window.__fp.layout.floors.reduce((n, f) => n + f.walls.length, 0)") > 0)
kiosk = b.new_page(extra_http_headers={"X-Remote-User-Name": "admin"}); kiosk.goto(BASE + "?debug=1&house=Eltern"); kiosk.wait_for_function("window.__fp && window.__fp.houseId()", timeout=45000)
check("?house=<name> opens that house", kiosk.evaluate("window.__fp.houseId()") == h1, (kiosk.evaluate("window.__fp.houseId()"), h1))
kiosk.close()
pg6.evaluate(f"window.__fp.switchHouse('{h1}')"); pg6.wait_for_timeout(800)
pg6.click("#houseDelete"); pg6.wait_for_timeout(1000)
check("house can be deleted again", len(api("api/houses")) == 1)
pg6.close()
pg7 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pg7.goto(BASE + "?debug=1"); pg7.wait_for_timeout(1500)
fi = pg7.evaluate("""() => { const f = window.__fp.layout.floors.find(x => x.walls.length); const w = f.walls[0];
  w.openings = w.openings || []; w.openings.push({id:'wnd3', type:'window', style:'triple', pos: 1.0, width: 1.2, height:1.2, sill:0.9, paneEntities:['binary_sensor.p1','','binary_sensor.p3']}); return window.__fp.layout.floors.indexOf(f); }""")
pg7.click(f"#floorRail [data-floor=\"{fi}\"]"); pg7.evaluate("window.__fp.rebuild()"); pg7.wait_for_timeout(500)
pg7.evaluate("window.__fp.fakeState('binary_sensor.p3', 'on'); window.__fp.fakeState('binary_sensor.p1', 'off')")
tg = pg7.evaluate("window.__fp.paneTargets('wnd3')")
check("each pane follows its own sensor", len(tg) == 3 and tg[0] == 0 and tg[1] == 0 and tg[2] < 0, tg)
pg7.close()
# --- roller shutter on a window (#331): a tick in the properties, its own cover entity, the curtain follows the cover, a ball in the live mode
pgR = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgR.on("pageerror", lambda e: errors.append("PAGEERROR " + str(e)))
pgR.goto(BASE + "?debug=1&mode=edit"); pgR.wait_for_timeout(1500)
fiR = pgR.evaluate("""() => { const fs = window.__fp.layout.floors; const len = (w) => Math.hypot(w.b[0] - w.a[0], w.b[1] - w.a[1]);
  const f = fs.find(x => x.walls.some(w => len(w) > 2 && !(w.openings || []).length)); const w = f.walls.find(w => len(w) > 2 && !(w.openings || []).length);
  w.openings = [{id: 'wsh', type: 'window', style: 'double', pos: len(w) / 2, width: 1.0, height: 1.2, sill: 0.9, entity: 'binary_sensor.rauch'}]; return fs.indexOf(f); }""")
pgR.click(f"#floorRail [data-floor=\"{fiR}\"]"); pgR.evaluate("window.__fp.rebuild()"); pgR.wait_for_timeout(500)
pgR.evaluate("window.__fp.select('opening', 'wsh')"); pgR.wait_for_timeout(300)
check("shutter (#331): every window has the tick, off at first", pgR.locator("#openShutter").count() == 1 and not pgR.locator("#openShutter").is_checked())
pickers = pgR.locator("#propsBody .stack").count()
pgR.locator("#openShutter").check(); pgR.wait_for_timeout(400)
op = pgR.evaluate("JSON.stringify(window.__fp.layout.floors[window.__fp.floorIdx()].walls.flatMap(w => w.openings || []).find(o => o.id === 'wsh'))")
check("shutter (#331): the tick gives the window a shutter and a field for its own entity", '"shutter":true' in op and pgR.locator("#propsBody .stack").count() == pickers + 1, (op, pickers))
pgR.evaluate("() => { const o = window.__fp.layout.floors[window.__fp.floorIdx()].walls.flatMap(w => w.openings || []).find(o => o.id === 'wsh'); o.shutterEntity = 'cover.rollo'; window.__fp.rebuild(); }"); pgR.wait_for_timeout(400)
pgR.evaluate("window.__fp.fakeState('cover.rollo', 'closed')"); sc_closed = pgR.evaluate("window.__fp.shutterScale('wsh')")
pgR.evaluate("window.__fp.fakeState('cover.rollo', 'open')"); sc_open = pgR.evaluate("window.__fp.shutterScale('wsh')")
check("shutter (#331): the curtain is down while the cover is closed and rolled up while it is open", sc_closed == 1 and sc_open is not None and sc_open < 0.1, (sc_closed, sc_open))
sc_part, lab = pgR.evaluate("() => { window.__fp.states()['cover.rollo'] = { ...window.__fp.states()['cover.rollo'], state: 'open', position: 40 }; window.__fp.applyStates(); return [window.__fp.shutterScale('wsh'), window.__fp.badge('wsh')]; }")
check("shutter (#331): at 40 % open the curtain is 60 % down and the label over the window says 40 %", sc_part is not None and abs(sc_part - (0.05 + 0.95 * 0.6)) < 0.01 and lab and lab.startswith("↕") and "40" in lab, (sc_part, lab))
check("shutter (#331): an open shutter is no open window (the contact decides)", pgR.evaluate("window.__fp.paneTargets('wsh').every(v => v === 0)"), pgR.evaluate("window.__fp.paneTargets('wsh')"))
pgR.click("#modeSwitch button[data-mode=live]"); pgR.wait_for_timeout(1200)
pgR.evaluate("""() => { const f = window.__fp.layout.floors[window.__fp.floorIdx()], w = f.walls.find(w => (w.openings || []).some(o => o.id === 'wsh'));
  const L = Math.hypot(w.b[0] - w.a[0], w.b[1] - w.a[1]), mx = (w.a[0] + w.b[0]) / 2, mz = (w.a[1] + w.b[1]) / 2, nx = -(w.b[1] - w.a[1]) / L, nz = (w.b[0] - w.a[0]) / L;
  window.__fp.camAt(mx + nx * 6, window.__fp.elev(window.__fp.floorIdx()) + 4, mz + nz * 6, mx, mz); }"""); pgR.wait_for_timeout(800)
bs = pgR.evaluate("window.__fp.ballScreen('wsh')")
hit = bs and pgR.evaluate(f"window.__fp.liveHitAt({bs['x']}, {bs['y']})")
check("shutter (#331): the live mode shows a ball at the window that can be tapped", bool(bs) and hit and hit["id"] == "wsh", (bs, hit))
if bs:
    pgR.mouse.click(bs["x"], bs["y"]); pgR.wait_for_timeout(500)
check("shutter (#331): a tap opens up / stop / down", pgR.is_visible("#livePopup") and pgR.locator("#livePopup .shutterActs button").count() == 3, pgR.inner_text("#livePopup") if pgR.is_visible("#livePopup") else "no popup")
if pgR.locator("#livePopup .shutterActs button").count() == 3:
    pgR.locator("#livePopup .shutterActs button").nth(2).click(); pgR.wait_for_timeout(900)
check("shutter (#331): down closes the cover in Home Assistant", ["cover", "close_cover", "cover.rollo"] in ha_calls(), ha_calls()[-3:])
pgR.close()
# --- backup export / import
pg8 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pg8.on("dialog", lambda d: d.accept())
pg8.goto(BASE + "?debug=1&mode=edit"); pg8.wait_for_timeout(1500)
bk = pg8.evaluate("fetch('api/backup').then(r => r.json())")
check("backup contains houses, settings and files", bk["format"] == "floorplan3d-backup" and len(bk["houses"]) >= 1 and "models" in bk, list(bk))
Path(f"{S}/backup.json").write_text(json.dumps(bk))
n_walls = pg8.evaluate("window.__fp.layout.floors.reduce((n, f) => n + f.walls.length, 0)")
pg8.evaluate("window.__fp.layout.floors.forEach(f => { f.walls.length = 0; }); window.__fp.layout.floors[0].name = 'kaputt'")
pg8.evaluate("fetch('api/layout', {method:'PUT', headers:{'Content-Type':'application/json'}, body: JSON.stringify(window.__fp.layout)})"); pg8.wait_for_timeout(500)
pg8.evaluate("document.querySelector('#housePanel').open = true")
pg8.set_input_files("#backupFile", f"{S}/backup.json"); pg8.wait_for_timeout(3000)
n2 = sum(len(f["walls"]) for f in api("api/layout")["floors"])
check("backup import restores the layout", n2 == n_walls and n_walls > 0, (n_walls, n2))
pg8.close()
# --- lock checkbox in the object list (any item)
pg9 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pg9.goto(BASE + "?debug=1&mode=edit"); pg9.wait_for_timeout(1500)
fi9 = pg9.evaluate("window.__fp.layout.floors.findIndex(f => f.walls.length && f.devices.length)")
pg9.click(f"#floorRail [data-floor=\"{max(fi9, 0)}\"]"); pg9.wait_for_timeout(600)
pg9.evaluate("document.querySelectorAll('#objList details').forEach(d => { d.open = true; })"); pg9.wait_for_timeout(200)
ngrp = pg9.locator("#objList details > summary").count()
pg9.fill("#objList .objfilter", "zzzz-nothing"); pg9.wait_for_timeout(200)
nfilt = pg9.locator("#objList details").count()
pg9.fill("#objList .objfilter", ""); pg9.wait_for_timeout(200)
pg9.evaluate("document.querySelectorAll('#objList details').forEach(d => { d.open = true; })")
check("object list is grouped and filterable", ngrp >= 2 and nfilt == 0, (ngrp, nfilt))
nl = pg9.locator("#objList .objlock").count()
check("object list has a lock checkbox per item", nl >= 4, nl)
count_locked = "window.__fp.layout.floors.flatMap(f => [...f.rooms, ...f.walls, ...f.walls.flatMap(w => w.openings || []), ...f.devices, ...(f.blocks || [])]).filter(x => x.locked).length"   # doors and windows have a lock box too
locked0 = pg9.evaluate(count_locked)                       # an earlier step may have left an item locked: compare the change, not an absolute number
idx = pg9.evaluate("[...document.querySelectorAll('#objList details[open] .objlock')].findIndex(c => !c.checked)")
pg9.locator("#objList details[open] .objlock").nth(idx).check(); pg9.wait_for_timeout(300)
locked = pg9.evaluate(count_locked)
check("ticking the box locks the item", locked == locked0 + 1, (locked0, locked))
w0 = pg9.evaluate("document.querySelector('#panel').getBoundingClientRect().width")
bx = pg9.evaluate("(() => { const r = document.querySelector('#panelResizer').getBoundingClientRect(); return [r.x + r.width / 2, r.y + 200]; })()")
pg9.mouse.move(bx[0], bx[1]); pg9.mouse.down(); pg9.mouse.move(bx[0] - 150, bx[1], steps=5); pg9.mouse.up(); pg9.wait_for_timeout(300)
w1 = pg9.evaluate("document.querySelector('#panel').getBoundingClientRect().width")
check("side panel can be widened by dragging its edge", w1 > w0 + 100, (w0, w1))
pg9.close()
