"""Kitchen run (#124), meters and the power add-on (#136): cables, battery, power editor; narrow wall pieces (#142).
"""
# --- kitchen run (#124): place, change shape, edit modules
pgK2 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgK2.on("pageerror", lambda e: errors.append("PAGEERROR " + str(e)))
pgK2.goto(BASE + "?debug=1&mode=edit"); pgK2.wait_for_timeout(1500)
pgK2.click("#view2d"); pgK2.wait_for_timeout(500)
pgK2.click("button[data-tool=device]"); pgK2.select_option("#entitySelect", "")
pgK2.fill("#paletteSearch", "kitchenrun"); pgK2.wait_for_timeout(200)
pgK2.click("#paletteGrid button.dev >> nth=0")
pgK2.evaluate("window.__fp.plan().fit && window.__fp.plan().fit()"); pgK2.wait_for_timeout(300)
pgK2.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].rooms.push({id:'kr1', name:'Kueche', color:'#888', points:[[40,40],[46,40],[46,44],[40,44]]}); window.__fp.rebuild()")
pgK2.evaluate("window.__fp.plan().fit && window.__fp.plan().fit()"); pgK2.wait_for_timeout(300)
c = pgK2.evaluate("window.__fp.plan().toClient(43,42)"); pgK2.mouse.click(*c); pgK2.wait_for_timeout(400)
kr = lambda: pgK2.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].devices.find(d => d.type === 'kitchenrun')")
k = kr()
check("kitchen run: placed with a straight default run and wall cabinets", k and len(k["legs"]) == 1 and len(k["legs"][0]) == 7 and k["upper"] is True, k)
pgK2.click("button[data-tool=select]")
c = pgK2.evaluate("window.__fp.plan().toClient(43,42)"); pgK2.mouse.click(*c); pgK2.wait_for_timeout(300)
check("kitchen run: properties show shape, wall cabinets and the modules", pgK2.is_visible("#kitchenShape") and pgK2.locator(".kitchenMod").count() == 7, pgK2.locator(".kitchenMod").count())
pgK2.select_option("#kitchenShape", "2"); pgK2.wait_for_timeout(300)
check("kitchen run: L-shape adds a second leg", len(kr()["legs"]) == 2 and pgK2.locator(".kitchenLeg").count() == 2, kr())
pgK2.locator(".kitchenAdd").first.click(); pgK2.wait_for_timeout(300)
check("kitchen run: + Module adds a module", len(kr()["legs"][0]) == 8)
pgK2.locator(".kitchenMod button >> nth=2").first.click(); pgK2.wait_for_timeout(300)
check("kitchen run: x removes a module", len(kr()["legs"][0]) == 7)
di = kr()["legs"][0].index("dish")
wdn = pgK2.locator(".kitchenMod .kitchenW").nth(di)
wdn.fill(str(round(float(wdn.input_value()) * 0.75, 4))); wdn.dispatch_event("change"); pgK2.wait_for_timeout(400)      # 0.6 m -> 0.45 m, in whatever unit the page shows
nw = kr()["legs"][0][di]
check("kitchen run: one module can be made narrower (own width)", isinstance(nw, dict) and nw["m"] == "dish" and abs(nw["w"] - 0.45) < 0.02, kr()["legs"][0])
check("kitchen run: the dishwasher is in the module list under its name", "Dishwasher" in pgK2.locator(".kitchenMod select").first.inner_text() or "Spülmaschine" in pgK2.locator(".kitchenMod select").first.inner_text(), pgK2.locator(".kitchenMod select").first.inner_text())
pgK2.click("#view3d"); pgK2.wait_for_timeout(800)
check("kitchen run: built in 3D without errors", True)
pgK2.click("button[data-tool=device]"); pgK2.fill("#paletteSearch", ""); pgK2.wait_for_timeout(200)
pgK2.fill("#paletteSearch", "solar"); pgK2.wait_for_timeout(200)
check("power: the library finds the solar panel", pgK2.locator("#paletteGrid button.dev").count() == 1, pgK2.locator("#paletteGrid button.dev").count())
pgK2.fill("#paletteSearch", "inverter"); pgK2.wait_for_timeout(200)
check("power: the library finds the inverter", pgK2.locator("#paletteGrid button.dev").count() == 1)
pgK2.fill("#paletteSearch", "zähler"); pgK2.wait_for_timeout(200)
check("meters (#136): the library finds power, water, gas and heat meter", pgK2.locator("#paletteGrid button.dev").count() == 4, pgK2.locator("#paletteGrid button.dev").count())
pgK2.evaluate("""() => { const f = window.__fp.layout.floors[window.__fp.floorIdx()];
  f.devices.push({id: 'mW', type: 'watermeter', x: 60, z: 60, y: 0.5, rot: 0, scale: 1, name: '', entity: 'sensor.water_test'},
                 {id: 'mG', type: 'gasmeter', x: 61, z: 60, y: 1.2, rot: 0, scale: 1, name: '', entity: 'sensor.gas_test'},
                 {id: 'mH', type: 'heatmeter', x: 62, z: 60, y: 1.0, rot: 0, scale: 1, name: '', entity: 'sensor.heat_test'});
  window.__fp.fakeState('sensor.water_test', '1234.567', 'm³'); window.__fp.fakeState('sensor.gas_test', '845.21', 'm³'); window.__fp.fakeState('sensor.heat_test', '5321', 'kWh');
  window.__fp.rebuild(); window.__fp.applyStates(); }""")
pgK2.wait_for_timeout(500)
check("meters (#136): water, gas and heat meter are built in 3D", all(pgK2.evaluate(f"window.__fp.has('{i}')") for i in ("mW", "mG", "mH")))
bw, bg, bh = (pgK2.evaluate(f"window.__fp.badge('{i}')") for i in ("mW", "mG", "mH"))
check("meters (#136): the badges show the reading with its own sign", (bw or "").startswith("🚰 1234.6 m³") and (bg or "").startswith("🔥 845.2 m³") and (bh or "").startswith("♨ 5321 kWh"), (bw, bg, bh))
mp = pgK2.inner_text("#meterPill") if pgK2.is_visible("#meterPill") else "hidden"
ep = pgK2.inner_text("#energyPill") if pgK2.is_visible("#energyPill") else ""
check("meters (#245): water, gas and heat in a pill of their own, not in the power overview", "🚰 1234.6 m³" in mp and "🔥 845.2 m³" in mp and "🚰" not in ep, (mp, ep))
pgK2.close()

# --- power add-on (#136): cable between solar panel and inverter
pgW = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgW.on("pageerror", lambda e: errors.append("PAGEERROR " + str(e)))
pgW.goto(BASE + "?debug=1&mode=edit"); pgW.wait_for_timeout(1500)
pgW.evaluate("""() => { const f = window.__fp.layout.floors[window.__fp.floorIdx()];
  f.devices.push({id: 'pw1', type: 'solarpanel', x: 70, z: 70, y: 0, rot: 0, scale: 1, name: 'PV', entity: 'sensor.pv_test', feeds: 'pw2'},
                 {id: 'pw2', type: 'inverter', x: 73, z: 70, y: 1.2, rot: 0, scale: 1, name: 'WR', entity: ''});
  window.__fp.fakeState('sensor.pv_test', '1500'); window.__fp.rebuild(); }""")
pgW.wait_for_timeout(600)
check("power: the Power button appears once the house has a power device", pgW.is_visible("#powerBtn"))
check("power: cables are off until the button is pressed", pgW.evaluate("window.__fp.powerInfo()")["flows"] == [] or not pgW.evaluate("window.__fp.powerInfo()")["shown"])
pgW.click("#powerBtn"); pgW.wait_for_timeout(600)
for _ in range(5):                                       # a periodic refresh of all states can wipe the fake value: set it again until the cable shows it
    pi = pgW.evaluate("window.__fp.powerInfo()")
    if pi["flows"] and pi["flows"][0]["active"] and pi["labels"] == 1: break
    pgW.evaluate("window.__fp.fakeState('sensor.pv_test', '1500'); window.__fp.rebuild()"); pgW.wait_for_timeout(400)
pi = pgW.evaluate("window.__fp.powerInfo()")
check("power: the button shows one cable with flowing dots and a watt label", pi["shown"] and len(pi["flows"]) == 1 and pi["flows"][0]["active"] and pi["flows"][0]["dir"] == 1 and pi["flows"][0]["dots"] == 8 and pi["labels"] == 1, pi)
if "1.50 kW" not in (pgW.inner_text("#energyPill") if pgW.is_visible("#energyPill") else ""):
    pgW.evaluate("window.__fp.fakeState('sensor.pv_test', '1500'); window.__fp.rebuild()"); pgW.wait_for_timeout(500)
check("power: the overview next to the room menu shows the production", pgW.is_visible("#energyPill") and "1.50 kW" in pgW.inner_text("#energyPill"), pgW.inner_text("#energyPill") if pgW.is_visible("#energyPill") else "hidden")
pgW.evaluate("""() => { const f = window.__fp.layout.floors[window.__fp.floorIdx()];
  f.devices.push({id: 'pwb', type: 'battery', x: 76, z: 70, y: 0, rot: 0, scale: 1, name: 'Bat', entity: 'sensor.bat_pct', batPower: 'sensor.bat_w'});
  window.__fp.fakeState('sensor.bat_pct', '82', '%'); window.__fp.fakeState('sensor.bat_w', '600', 'W'); window.__fp.rebuild(); }""")
pgW.wait_for_timeout(600)
bt = pgW.inner_text("#energyPill")
check("power: the overview shows the battery level and that it charges (arrow up and watts)", "82 %" in bt and "↑" in bt and "600 W" in bt, bt)
pgW.evaluate("window.__fp.fakeState('sensor.bat_w', '-450', 'W'); window.__fp.rebuild()"); pgW.wait_for_timeout(600)
bt = pgW.inner_text("#energyPill")
check("power: a negative value shows that it discharges (arrow down)", "↓" in bt and "450 W" in bt, bt)
pgW.evaluate("window.__fp.fakeState('sensor.bat_w', '0', 'W'); window.__fp.rebuild()"); pgW.wait_for_timeout(600)
check("power: no flow, no arrow", "82 %" in pgW.inner_text("#energyPill") and "↑" not in pgW.inner_text("#energyPill") and "↓" not in pgW.inner_text("#energyPill"), pgW.inner_text("#energyPill"))
pgW.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].devices = window.__fp.layout.floors[window.__fp.floorIdx()].devices.filter(d => d.id !== 'pwb'); window.__fp.rebuild()"); pgW.wait_for_timeout(300)
pgW.evaluate("window.__fp.fakeState('sensor.pv_test', '-300'); window.__fp.rebuild()"); pgW.wait_for_timeout(600)
check("power: a negative value runs the dots backwards", pgW.evaluate("window.__fp.powerInfo()")["flows"][0]["dir"] == -1, pgW.evaluate("window.__fp.powerInfo()"))
pgW.click("#powerBtn"); pgW.wait_for_timeout(300)
check("power: pressing again hides the cables", pgW.evaluate("window.__fp.powerInfo()")["flows"] == [])
pgW.close()

# --- power editor (#136): only power things, several cables from one device, routes
pgE = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgE.on("pageerror", lambda e: errors.append("PAGEERROR " + str(e)))
pgE.goto(BASE + "?debug=1&mode=edit"); pgE.wait_for_timeout(1500)
pgE.evaluate("""() => { const L = window.__fp.layout; const dv = (id, type, x, z, y) => ({id, type, x, z, y, rot: 0, scale: 1, name: id, entity: ''});
  L.floors.push({id: 'ef', name: 'Strom', kind: 'floor', walls: [], rooms: [{id: 'er', name: 'R', points: [[0,0],[6,0],[6,5],[0,5]]}],
    devices: [dv('he', 'houseentry', 1, 1, 0), dv('fb', 'fusebox', 3, 1, 1.4), dv('bt', 'battery', 5, 1, 0), dv('lp', 'light', 3, 4, 2)], blocks: [], stairs: []});
  window.__fp.switchFloor(L.floors.length - 1); window.__fp.rebuild(); }""")
pgE.wait_for_timeout(500)
pgE.click("#view2d"); pgE.wait_for_timeout(400)
pgE.evaluate("window.__fp.plan().fit()"); pgE.wait_for_timeout(300)
check("power editor: the cable tool is hidden until the editor is on", not pgE.is_visible("#cableBtn"))
pgE.click("#powerEditBtn"); pgE.wait_for_timeout(500)
check("power editor: on, the cable tool shows and the library shows the power things", pgE.is_visible("#cableBtn") and pgE.evaluate("document.body.dataset.power") == "1")
check("power editor: other devices (the lamp) are hidden in 3D", pgE.evaluate("window.__fp.powerInfo().hidden") >= 1, pgE.evaluate("window.__fp.powerInfo()"))
pgE.evaluate("window.__fp.applyStates()"); pgE.wait_for_timeout(300)
check("power editor (#174): a state update does not bring the other devices back", pgE.evaluate("window.__fp.powerInfo().hidden") >= 1 and pgE.evaluate("document.body.dataset.power") == "1", pgE.evaluate("window.__fp.powerInfo()"))
pgE.evaluate("window.__fp.rebuild(); window.__fp.applyStates()"); pgE.wait_for_timeout(300)
check("power editor (#174): neither does a rebuilt scene", pgE.evaluate("window.__fp.powerInfo().hidden") >= 1, pgE.evaluate("window.__fp.powerInfo()"))
pgE.evaluate("() => { const d = window.__fp.layout.floors.at(-1).devices; d.push({id: 'wm', type: 'watermeter', x: 2, z: 3, y: 0.5, rot: 0, scale: 1, name: '', entity: ''}); window.__fp.rebuild(); window.__fp.applyStates(); }"); pgE.wait_for_timeout(300)
check("power editor (#207): a water meter stays visible in the power editor", pgE.evaluate("window.__fp.devPose('wm').visible") is True)
pgE.evaluate("() => { const d = window.__fp.layout.floors.at(-1).devices; d.splice(d.findIndex(v => v.id === 'wm'), 1); window.__fp.rebuild(); window.__fp.applyStates(); }"); pgE.wait_for_timeout(300)
check("power editor: the library opens at once with the power things", pgE.is_visible("#devicePalette") and pgE.locator("#paletteGrid button.dev").count() == 7 and pgE.locator("#paletteCats button.active").inner_text() == "Power", pgE.locator("#paletteGrid button.dev").count())
pgE.click("#cableBtn"); pgE.wait_for_timeout(200)
clk = lambda x, z: (lambda c: (pgE.mouse.move(*c), pgE.wait_for_timeout(120), pgE.mouse.click(*c), pgE.wait_for_timeout(250)))(pgE.evaluate("window.__fp.plan().toClient(%s,%s)" % (x, z)))
clk(3, 4); clk(1, 1)
cab = lambda: pgE.evaluate("(window.__fp.layout.floors.at(-1).devices.find(d => d.id === 'he').cables || [])")
check("power editor: the lamp cannot be wired (not a power thing)", cab() == [], cab())
clk(3, 1); clk(1, 1); clk(5, 1)
check("power editor: two clicks make a cable, a device can have several", len(cab()) == 2 and cab()[0]["route"] == "floor" and {c["to"] for c in cab()} == {"fb", "bt"}, cab())
pgE.wait_for_timeout(400)
pgE.click("#view3d"); pgE.wait_for_timeout(700)
check("power editor: both cables are drawn in 3D", len(pgE.evaluate("window.__fp.powerInfo().flows")) == 2, pgE.evaluate("window.__fp.powerInfo()"))
# 3D: only power devices can be hit, small ones are found near the pointer, the cable tool works with the mouse
lp = pgE.evaluate("window.__fp.screenOf('lp')")
check("power editor: a lamp (not a power thing) cannot be hit in 3D", pgE.evaluate("window.__fp.liveHitAt(%s, %s)" % (lp["x"], lp["y"])) is None, lp)
fbp = pgE.evaluate("window.__fp.screenOf('fb')")
check("power editor: a power device is found a few pixels beside its centre", (pgE.evaluate("window.__fp.liveHitAt(%s, %s)" % (fbp["x"] + 12, fbp["y"] + 12)) or {}).get("id") == "fb", fbp)
pgE.click("#cableBtn"); pgE.wait_for_timeout(200)
def on_device(did):
    """a spot on the screen where the device itself is hit: from some angles a cable on the floor lies over its centre and would take the click"""
    sp = pgE.evaluate("window.__fp.screenOf('%s')" % did)
    for dx, dy in ((0, 0), (0, -8), (-8, 0), (8, 0), (0, -16), (-12, -12), (12, -12), (0, 8)):
        if (pgE.evaluate("window.__fp.liveHitAt(%s, %s)" % (sp["x"] + dx, sp["y"] + dy)) or {}).get("id") == did:
            return sp["x"] + dx, sp["y"] + dy
    return sp["x"], sp["y"]
for did in ("fb", "bt"):
    x, y = on_device(did); pgE.mouse.move(x, y); pgE.wait_for_timeout(120); pgE.mouse.click(x, y); pgE.wait_for_timeout(300)
fbc = pgE.evaluate("(window.__fp.layout.floors.at(-1).devices.find(d => d.id === 'fb').cables || []).map(c => c.to)")
check("power editor: the cable tool also works with clicks in 3D", fbc == ["bt"], fbc)
pgE.click("#view2d"); pgE.wait_for_timeout(400)
pgE.click("button[data-tool=select]"); pgE.wait_for_timeout(200)
c = pgE.evaluate("window.__fp.plan().toClient(1,1)"); pgE.mouse.click(*c); pgE.wait_for_timeout(400)
check("power editor: the properties list both cables with a route each", pgE.locator(".cableRow").count() == 2 and pgE.locator(".cableRoute").count() == 2, pgE.locator(".cableRow").count())
pgE.locator(".cableRoute").first.select_option("through"); pgE.wait_for_timeout(300)
check("power editor: the route can be changed", cab()[0]["route"] == "through", cab())
pgE.locator(".cableRow button").first.click(); pgE.wait_for_timeout(300)
check("power editor: the cross removes one cable", len(cab()) == 1, cab())
c = pgE.evaluate("window.__fp.plan().toClient(1.8,1)"); pgE.mouse.click(*c); pgE.wait_for_timeout(400)
check("power cables: a click on the cable line in 2D picks the cable (properties with kind, route, delete)", pgE.is_visible("#cableDel") and pgE.is_visible("#cableKind") and pgE.locator("#cableKind").input_value() == "grid", pgE.evaluate("document.querySelector('#propsTitle').innerText"))
pgE.select_option("#cableKind", "solar"); pgE.wait_for_timeout(300)
check("power cables: the kind (colour) can be changed per cable", cab()[0].get("kind") == "solar", cab())
pgE.click("#cableDel"); pgE.wait_for_timeout(400)
check("power cables: the delete button removes the picked cable", cab() == [], cab())
pgE.click("#powerEditBtn"); pgE.wait_for_timeout(400)
check("power editor: off again, the lamp is back and the cable tool is gone", pgE.evaluate("window.__fp.powerInfo().hidden") == 0 and not pgE.is_visible("#cableBtn"), pgE.evaluate("window.__fp.powerInfo()"))
was = pgE.evaluate("window.__fp.powerInfo().shown")
pgE.click("#powerBtn"); pgE.wait_for_timeout(300)
pgE.evaluate("window.__fp.applyStates(); window.__fp.rebuild(); window.__fp.applyStates()"); pgE.wait_for_timeout(600)
check("power button (#174): a real switch: after a press it stays as it is, also after state updates", pgE.evaluate("window.__fp.powerInfo().shown") == (not was) and pgE.locator("#powerBtn.active").count() == (0 if was else 1), (was, pgE.evaluate("window.__fp.powerInfo()")))
pgE.click("#powerBtn"); pgE.wait_for_timeout(300)
check("power button (#174): the next press switches it back", pgE.evaluate("window.__fp.powerInfo().shown") == was)
pgE.click("#view2d"); pgE.wait_for_timeout(400)
pgE.click("#powerEditBtn"); pgE.wait_for_timeout(400)
pgE.locator("#paletteCats button").first.click(); pgE.fill("#paletteSearch", "bridge"); pgE.wait_for_timeout(200)
pgE.locator("#paletteGrid button.dev").first.click(); pgE.wait_for_timeout(200)
c = pgE.evaluate("window.__fp.plan().toClient(3, 2.5)"); pgE.mouse.click(*c); pgE.wait_for_timeout(500)
br = pgE.evaluate("(window.__fp.layout.floors.at(-1).devices.find(d => d.type === 'bridge') || {}).id")
check("power editor (#207): placing something else (a bridge) switches the editor off, so it is visible at once", br and pgE.evaluate("document.body.dataset.power") != "1" and pgE.evaluate(f"window.__fp.devPose('{br}').visible") is True, (br, pgE.evaluate("document.body.dataset.power")))
pgE.close()

# --- narrow wall pieces (#142): the opening shrinks to what is left instead of being refused
pgN = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgN.on("pageerror", lambda e: errors.append("PAGEERROR " + str(e)))
pgN.goto(BASE + "?debug=1&mode=edit"); pgN.wait_for_timeout(1500)
pgN.evaluate("(() => { const L = window.__fp.layout; L.floors.push({id:'nf', name:'N', kind:'floor', walls:[{id:'nw1', a:[0,0], b:[0.5,0], thickness:0.2, height:2.6, openings:[]}, {id:'nw2', a:[0,2], b:[0.06,2], thickness:0.2, height:2.6, openings:[]}, {id:'nw3', a:[2,0], b:[2,2], thickness:0.2, height:2.6, openings:[]}], rooms:[], devices:[], blocks:[], stairs:[]}); window.__fp.switchFloor(L.floors.length - 1); window.__fp.rebuild(); })()")
pgN.click("#view2d"); pgN.wait_for_timeout(500)
pgN.click("button[data-tool=opening]"); pgN.wait_for_timeout(200)
pgN.evaluate("window.__fp.plan().fit()"); pgN.wait_for_timeout(300)
nwo = lambda wid: pgN.evaluate("(window.__fp.layout.floors[window.__fp.floorIdx()].walls.find(w => w.id === '%s').openings || []).map(o => o.width)" % wid)
c = pgN.evaluate("window.__fp.plan().toClient(0.25,0)"); pgN.mouse.move(*c); pgN.wait_for_timeout(200); pgN.mouse.click(*c); pgN.wait_for_timeout(400)
ow = nwo("nw1")
check("narrow wall: an opening is placed anyway, shrunk to fit (0.4 m at most)", len(ow) == 1 and 0.1 <= ow[0] <= 0.4, ow)
c = pgN.evaluate("window.__fp.plan().toClient(0.03,2)"); pgN.mouse.move(*c); pgN.wait_for_timeout(200); pgN.mouse.click(*c); pgN.wait_for_timeout(400)
check("narrow wall: a piece too short for any opening still refuses", nwo("nw2") == [], nwo("nw2"))
pgN.close()
