"""Tablets and phones: offline list, open windows, alerts (#58), search (#62), phone menu and status, kiosk (#61).
"""
# --- tablet: offline devices, pills that scroll sideways, low-power mode, no grid in live mode
pg17 = b.new_page(viewport={"width": 760, "height": 1000}, has_touch=True, extra_http_headers={"X-Remote-User-Name": "admin"})
pg17.on("pageerror", lambda e: errors.append("PAGEERROR " + str(e)))
pg17.goto(BASE + "?debug=1&mode=live"); pg17.wait_for_timeout(1500)
pg17.evaluate("(() => { const L = window.__fp.layout; window.__keep = L.floors.map(f => f.devices); L.floors.forEach(f => f.devices = []); window.__fp.rebuild(); })()"); pg17.wait_for_timeout(400)
status_open(pg17)
check("offline: the pill is there with nothing offline too", pg17.locator("#offlinePill.ok").is_visible() and "0" in pg17.inner_text("#offlinePill"), pg17.inner_text("#offlinePill"))
pg17.evaluate("(() => { const L = window.__fp.layout; L.floors.forEach((f, i) => f.devices = window.__keep[i]); window.__fp.rebuild(); })()"); pg17.wait_for_timeout(400)
urllib.request.urlopen(HA + "/_set?e=switch.garage&s=unavailable"); pg17.wait_for_timeout(1200)
check("offline: an entity that is not placed in the plan is not listed", not [x for x in pg17.evaluate("window.__fp.offline()") if x["entity"] == "switch.garage"])
urllib.request.urlopen(HA + "/_set?e=switch.garage&s=off"); pg17.wait_for_timeout(800)
pg17.evaluate("""(() => { const f = window.__fp.layout.floors[window.__fp.floorIdx()];
  f.devices.push({ id: 'offA', type: 'sensor', x: 1, z: 1, y: 1.8, rot: 0, scale: 1, name: 'Temp-Sensor', entity: 'sensor.temp' },
                 { id: 'offB', type: 'light', x: 2, z: 1, y: 2.5, rot: 0, scale: 1, name: 'Alte Lampe', entity: 'light.gibtesnicht' },
                 { id: 'offC', type: 'spot', x: 3, z: 1, y: 2.5, rot: 0, scale: 1, name: 'Spot ohne Entität', entity: '' },
                 { id: 'offD', type: 'sofa', x: 3, z: 2, y: 0, rot: 0, scale: 1, name: 'Sofa', entity: '' });
  window.__fp.rebuild(); })()""")
pg17.wait_for_timeout(500)
off = pg17.evaluate("window.__fp.offline().filter(x => x.id.startsWith('off')).map(x => [x.id, x.reason])")
check("offline: a missing entity and a lamp without entity are listed, furniture is not", off == [["offB", "missing"], ["offC", "unlinked"]], off)
urllib.request.urlopen(HA + "/_set?e=sensor.temp&s=unavailable"); pg17.wait_for_timeout(1200)
off = pg17.evaluate("window.__fp.offline().filter(x => x.id.startsWith('off')).map(x => [x.id, x.reason])")
status_open(pg17)
check("offline: an unavailable device shows up at once (live)", ["offA", "unavailable"] in off and pg17.locator("#offlinePill").is_visible(), off)
status_open(pg17)
pg17.click("#offlinePill"); pg17.wait_for_timeout(300)
n_items = pg17.locator("#offlineList li").count()
pg17.screenshot(path=os.path.join(S, "offline.png"))
pg17.locator("#offlineList li button", has_text="Temp-Sensor").click(); pg17.wait_for_timeout(500)
check("offline: the list opens, a tap shows the device", n_items >= 2 and not pg17.locator("#offlineDialog[open]").count() and pg17.locator("#livePopup").is_visible(), n_items)
near_cam = lambda p, d: abs(sum((a - b) ** 2 for a, b in zip(pg17.evaluate("window.__fp.cam()"), p)) ** 0.5 - d) < 0.15
e17 = pg17.evaluate("window.__fp.elev(window.__fp.floorIdx())")
check("offline (#215): the tap flies the camera to the device like the search", near_cam([1, e17 + 1.8, 1], 5.5), pg17.evaluate("window.__fp.cam()"))
pg17.keyboard.press("Escape"); pg17.wait_for_timeout(200)
pg17.evaluate("""(() => { const f = window.__fp.layout.floors[window.__fp.floorIdx()];
  f.walls.push({ id: 'jw', a: [20, 0], b: [24, 0], thickness: 0.2, height: 2.6, openings: [{ id: 'jwin', type: 'window', pos: 2, width: 1.2, height: 1.2, sill: 0.9, entity: 'binary_sensor.rauch', name: 'Sprungfenster' }] });
  window.__fp.rebuild(); })()""")
urllib.request.urlopen(HA + "/_set?e=binary_sensor.rauch&s=on"); pg17.wait_for_timeout(1200)
status_open(pg17)
pg17.click("#openPill"); pg17.wait_for_timeout(300)
pg17.locator("#openList li button", has_text="Sprungfenster").click(); pg17.wait_for_timeout(500)
check("open list (#215): a tap on an open window flies the camera there like the search", not pg17.locator("#openDialog[open]").count() and near_cam([22, e17 + 1.5, 0], 5.5), pg17.evaluate("window.__fp.cam()"))
urllib.request.urlopen(HA + "/_set?e=binary_sensor.rauch&s=off"); pg17.wait_for_timeout(800)
pg17.keyboard.press("Escape"); pg17.evaluate("(() => { const f = window.__fp.layout.floors[window.__fp.floorIdx()]; f.walls.splice(f.walls.findIndex(w => w.id === 'jw'), 1); window.__fp.rebuild(); })()"); pg17.wait_for_timeout(3800)   # the marker ring of the jump is gone again
urllib.request.urlopen(HA + "/_set?e=sensor.temp&s=21.5"); pg17.wait_for_timeout(1200)
check("offline: back online, off the list", not [x for x in pg17.evaluate("window.__fp.offline()") if x["id"] == "offA"])
mem = [pg17.evaluate("(() => { window.__fp.rebuild(); window.__fp.frame(); return window.__fp.renderer.info.memory.geometries; })()") for _ in range(4)]
check("tablet: rebuilding the scene does not leak graphics memory", mem[0] == mem[-1], mem)
check("tablet: low-power mode without blur", pg17.evaluate("window.__fp.LOW && document.body.classList.contains('low')"))
check("live: no grid", not pg17.evaluate("window.__fp.earthDbg()")["gridShown"])
# tablets: a row too long for the screen scrolls with arrows (upright phones wrap it into more rows instead); a wide stand-in makes it too long
pg17.set_viewport_size({"width": 1000, "height": 1000}); pg17.wait_for_timeout(400)
pg17.evaluate("(() => { const s = document.createElement('span'); s.id = 'navFill'; s.className = 'pill'; s.style.width = '2000px'; window.__fp.navBar().append(s); window.__fp.navBar().scrollLeft = 0; })()"); pg17.wait_for_timeout(300)
ar = pg17.evaluate("window.__fp.navArrows()")
pg17.click("#navRight"); pg17.wait_for_timeout(700)
ar2 = pg17.evaluate("[window.__fp.navBar().scrollLeft, ...window.__fp.navArrows()]")
check("tablet: pills that do not fit get arrows and scroll", ar == [False, True] and ar2[0] > 0 and ar2[1], (ar, ar2))
pg17.evaluate("(() => { document.getElementById('navFill').remove(); window.__fp.navBar().scrollLeft = 0; })()"); pg17.wait_for_timeout(300)
pg17.set_viewport_size({"width": 760, "height": 1000}); pg17.wait_for_timeout(400)
nbw = pg17.evaluate("(() => { const n = window.__fp.navBar(); return [n.scrollWidth, n.clientWidth, ...window.__fp.navArrows()]; })()")
check("phone upright: the row at the top fits on the screen (wraps, no arrows)", nbw[0] <= nbw[1] + 1 and pg17.locator("#navRight").is_hidden(), nbw)
# --- warnings (#58), search (#62), wall-tablet kiosk (#61)
pg17.evaluate("""(() => { const f = window.__fp.layout.floors[window.__fp.floorIdx()];
  if (!f.rooms.some(r => r.id === 'alRoom')) f.rooms.push({ id: 'alRoom', name: 'Rauchküche', points: [[20, 20], [24, 20], [24, 23], [20, 23]] });
  f.devices.push({ id: 'alSmoke', type: 'smoke', x: 22, z: 21.5, y: 2.5, rot: 0, scale: 1, name: 'Rauchmelder Küche', entity: 'binary_sensor.rauch' });
  window.__fp.rebuild(); })()""")
pg17.wait_for_timeout(400)
check("alerts: nothing while the smoke sensor is off", pg17.evaluate("window.__fp.alerts().length") == 0 and pg17.locator("#alertBar").is_hidden())
urllib.request.urlopen(HA + "/_set?e=binary_sensor.rauch&s=on"); pg17.wait_for_timeout(1500)
al = pg17.evaluate("window.__fp.alerts()")
check("alerts: smoke shows a banner and the room pulses red", len(al) == 1 and al[0]["kind"] == "smoke" and al[0]["at"]["roomId"] == "alRoom"
      and pg17.locator("#alertBar .alertItem").is_visible() and pg17.evaluate("window.__fp.alertPulsing()") >= 1, al)
pg17.screenshot(path=os.path.join(S, "alert.png"))
pg17.click("#alertBar .alertItem"); pg17.wait_for_timeout(800)
check("alerts: a tap on the warning jumps into the room", pg17.locator("#roomPanel").is_visible())
urllib.request.urlopen(HA + "/_set?e=binary_sensor.rauch&s=off"); pg17.wait_for_timeout(1500)
check("alerts: gone when the sensor is off again", pg17.evaluate("window.__fp.alerts().length") == 0 and pg17.locator("#alertBar").is_hidden())
pg17.click("#findBtn"); pg17.wait_for_timeout(300); pg17.fill("#findInput", "rauchmel"); pg17.wait_for_timeout(300)
check("search: finds a device by part of its name", "Rauchmelder Küche" in pg17.inner_text("#findList"), pg17.inner_text("#findList"))
pg17.keyboard.press("Enter"); pg17.wait_for_timeout(800)
check("search: Enter goes to the first hit and shows it", pg17.locator("#findBox").is_hidden() and pg17.locator("#livePopup").is_visible())
# phones: the tool bar is folded into the ☰ menu at the top left and opens as a drop-down list
check("phone menu: tool bar folded, ☰ shown", pg17.locator("#tbMenuBtn").is_visible() and pg17.locator("#toolbar").is_hidden())
pg17.click("#tbMenuBtn"); pg17.wait_for_timeout(300)
check("phone menu: ☰ opens the tool bar as a list", pg17.locator("#toolbar").is_visible() and pg17.locator("#fitBtn").is_visible())
check("phone (#299): only live and 3D, no Edit, no 2D, no users", pg17.locator("#modeSwitch").is_hidden() and pg17.locator("#view2d").is_hidden()
      and pg17.locator("#viewSplit").is_hidden() and pg17.locator("#usersBtn").is_hidden() and pg17.evaluate("document.body.classList.contains('live')"))
pg17.click("#fitBtn"); pg17.wait_for_timeout(300)
check("phone menu: a choice closes it again", pg17.locator("#toolbar").is_hidden() and pg17.locator("#tbMenuBtn").inner_text() == "☰")
pg17.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].devices = window.__fp.layout.floors[window.__fp.floorIdx()].devices.filter(d => d.id !== 'alSmoke')")
pg17.evaluate("Object.assign(window.__fp.settings(), { idleReturn: 1, idleOrbit: true, nightDim: 'time', nightFrom: '00:00', nightTo: '23:59' })")
# phones: three buttons at the top: ☰, the floor as a drop-down (phonenav.js) and the rooms, instead of the floor pills
check("phone nav: a floor button and the room button instead of the floor pills", pg17.locator("#phoneNavBtn").is_visible() and pg17.locator("#roomMenuBtn").is_visible() and pg17.locator("#floorPills").is_hidden(), pg17.inner_text("#phoneNavBtn"))
pg17.click("#phoneNavBtn"); pg17.wait_for_timeout(300)
nfl = pg17.evaluate("window.__fp.layout.floors.length")
check("phone nav: the floor list shows every floor", pg17.locator("#phoneNav").is_visible() and pg17.locator("#phoneNav .pill").count() >= nfl, pg17.inner_text("#phoneNav"))
pg17.locator("#phoneNav .pill.active").click(); pg17.wait_for_timeout(300)
check("phone nav: picking a floor closes the list", pg17.locator("#phoneNav").is_hidden())
# phones upright: power, offline, open, cameras fold into the 📊 drop-down; the search is at the top right (phonestatus.js)
check("phone status: the values are folded behind one button", pg17.locator("#phoneStatusBtn").is_visible() and pg17.locator("#offlinePill").is_hidden(), pg17.inner_text("#phoneStatusBtn"))
pg17.click("#phoneStatusBtn"); pg17.wait_for_timeout(300)
check("phone status: the button opens the values as a list", pg17.locator("#phoneStatus").is_visible() and pg17.locator("#phoneStatus #offlinePill").is_visible())
pg17.click("#phoneStatusBtn"); pg17.wait_for_timeout(300)
fb = pg17.evaluate("(() => { const r = document.getElementById('findBtn').getBoundingClientRect(); return [r.top, r.right, innerWidth]; })()")
check("phone status: the search button is at the top right", pg17.locator("#phoneStatus").is_hidden() and fb[0] < 60 and fb[1] > fb[2] - 30, fb)
pg17.click("#roomMenuBtn"); pg17.locator("#roomMenu .pill", has_text="Rauchküche").click(); pg17.wait_for_timeout(600)
check("phone nav: the room button opens the room and names it", pg17.locator("#roomPanel").is_visible() and "Rauchküche" in pg17.inner_text("#roomMenuBtn"), pg17.inner_text("#roomMenuBtn"))
pg17.evaluate("window.__fp.kioskIdle(2 * 60000); window.__fp.kioskTick()"); pg17.wait_for_timeout(800)
check("kiosk: after the idle time the start view returns and the house turns", pg17.locator("#roomPanel").is_hidden() and pg17.evaluate("window.__fp.autoRotate()"))
check("kiosk: dimmed at night", pg17.locator("#nightDim").is_visible())
pg17.mouse.click(300, 400); pg17.wait_for_timeout(300)
check("kiosk: a touch wakes the screen and stops the turning", pg17.locator("#nightDim").is_hidden() and not pg17.evaluate("window.__fp.autoRotate()"))
pg17.evaluate("Object.assign(window.__fp.settings(), { idleReturn: 0, idleOrbit: false, nightDim: 'off' })")
pg17.close()
