"""Floors and views of an imported house: floor rail, floor cards, half section, arrow keys, cameras (#69), room panel (#67), automatic rooms (#17), pull apart, view menu, see-through walls.
"""
# --- floor rail, floor cards, half section, arrow keys, stairs, frameless opening
ex = json.load(open(os.path.join(S, "..", "..", "docs", "examples", "house.json")))
imp = urllib.request.Request(BASE + "api/import", data=json.dumps(ex).encode(), headers={"Content-Type": "application/json", "X-Remote-User-Name": "admin"})
hid = json.load(urllib.request.urlopen(imp))["id"]
pg13 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pg13.goto(BASE + f"?debug=1&mode=edit&house={hid}"); pg13.wait_for_timeout(2500)
nfl = pg13.evaluate("window.__fp.layout.floors.length")
check("rail: one thumbnail per floor, floor pills hidden", pg13.locator("#floorRail .floorThumb").count() == nfl and not pg13.locator("#floorPills").is_visible(), nfl)
check("rail: thumbnails are drawn", pg13.evaluate("[...document.querySelectorAll('#floorRail canvas')].every(c => c.getContext('2d').getImageData(0,0,c.width,c.height).data.some(v => v))"))
pg13.click('#floorRail [data-floor="1"]'); pg13.wait_for_timeout(500)
check("rail: a tap switches the floor and marks it", pg13.locator('#floorRail [data-floor="1"].active').count() == 1)
pg13.click("#floorRail .railHouse"); pg13.wait_for_timeout(1200)
cards = pg13.evaluate("window.__fp.houseCards()")
check("cards: one info card per floor in the whole-house view", len(cards) >= 2 and all("Rooms" in c and "Lights on" in c and "Windows open" in c for c in cards), cards)
nrooms = pg13.evaluate("window.__fp.layout.floors.reduce((a, f) => a + f.rooms.filter(r => r.name).length, 0)")
check("whole house: room buttons of every floor", pg13.locator("#roomMenu .pill:not(.all)").count() == nrooms and nrooms > 3, (pg13.locator("#roomMenu .pill:not(.all)").count(), nrooms))
pg13.click("#roomMenuBtn"); pg13.wait_for_timeout(300)
check("rooms: one drop-down instead of a row of buttons", pg13.locator("#roomMenu").is_visible() and pg13.locator("#roomMenu .rmHead").count() >= 2)
pg13.keyboard.press("Escape"); pg13.wait_for_timeout(200)
check("rooms: Esc closes the drop-down", not pg13.locator("#roomMenu").is_visible())
pg13.locator(".floorCard").first.click(); pg13.wait_for_timeout(500)
check("cards: a tap opens that floor", pg13.evaluate("window.__fp.houseMode()") is False and pg13.locator(".floorCard").count() == 0)
view_menu(pg13); pg13.click("#halfToggle"); pg13.wait_for_timeout(800)
clipped = pg13.evaluate("(() => { let n = 0; window.__fp.scene.traverse(o => { if (o.material && [].concat(o.material).some(m => m.clippingPlanes && m.clippingPlanes.some(p => p.normal.y === -1))) n++; }); return n; })()")
check("half section: the walls are cut", clipped > 0 and pg13.locator("#halfToggle.active").count() == 1, clipped)
view_menu(pg13); pg13.click("#halfToggle"); pg13.wait_for_timeout(500)
check("half section: off again", pg13.locator("#halfToggle.active").count() == 0)
lay13 = pg13.evaluate("window.__fp.layout")
dev = next(d for f in lay13["floors"] for d in f["devices"])
di = next(i for i, f in enumerate(lay13["floors"]) if dev in f["devices"])
pg13.click(f'#floorRail [data-floor="{di}"]'); pg13.wait_for_timeout(400)
pg13.evaluate(f"window.__fp.select('device', '{dev['id']}')")
x0 = dev["x"]
pg13.keyboard.press("ArrowRight"); pg13.wait_for_timeout(200)
d1 = next(d for f in pg13.evaluate("window.__fp.layout")["floors"] for d in f["devices"] if d["id"] == dev["id"])
check("arrow key moves the selection by one grid step", abs(d1["x"] - x0 - 0.25) < 1e-6, (x0, d1["x"]))
pg13.keyboard.press("Shift+ArrowLeft"); pg13.wait_for_timeout(200)
d2 = next(d for f in pg13.evaluate("window.__fp.layout")["floors"] for d in f["devices"] if d["id"] == dev["id"])
check("Shift + arrow moves by 10 cm", abs(d2["x"] - (d1["x"] - 0.1)) < 1e-6, (d1["x"], d2["x"]))
pg13.keyboard.press("Alt+ArrowDown"); pg13.wait_for_timeout(200)
d3 = next(d for f in pg13.evaluate("window.__fp.layout")["floors"] for d in f["devices"] if d["id"] == dev["id"])
check("Alt + arrow moves by 1 cm", abs(d3["z"] - d2["z"] - 0.01) < 1e-6, (d2["z"], d3["z"]))
pg13.click("button[data-tool=opening]")
check("group tool is gone", pg13.locator("button[data-tool=group]").count() == 0 and pg13.locator("#groupPalette").count() == 0)
# --- other floors as coloured outlines in the 2D plan: a switch with the colour legend in the corner of the plan
check("floors chip: hidden while only the 3D view is shown", not pg13.locator("#planFloorsChip").is_visible())
pg13.click("#view2d"); pg13.click('#floorRail [data-floor="1"]'); pg13.wait_for_timeout(500)
name0 = pg13.evaluate("window.__fp.layout.floors[0].name")
legend = lambda: pg13.evaluate("[...document.querySelectorAll('#planFloorsList li')].map(li => li.textContent)")
check("floors chip: switch and legend in the plan, the floor below with its colour", pg13.locator("#planFloorsBtn").is_visible() and name0 in legend(), (name0, legend()))
pg13.click("#planFloorsBtn"); pg13.click("#planFloorsBtn"); pg13.wait_for_timeout(300)
check("floors chip: switched off, the legend is empty but the switch stays", pg13.locator("#planFloorsBtn").is_visible() and legend() == [] and pg13.evaluate("localStorage.getItem('fp3d.planFloors')") == "off")
pg13.click("#planFloorsBtn"); pg13.wait_for_timeout(300)
check("floors chip: on again (below)", name0 in legend() and pg13.evaluate("localStorage.getItem('fp3d.planFloors')") == "below")
pg13.click("#view3d"); pg13.wait_for_timeout(400)
# --- cameras (#69) and the room panel (#67)
camapi = pg13.evaluate("fetch('api/camera/camera.flur').then(r => [r.status, r.headers.get('content-type')])")
check("camera still image comes through the add-on", camapi == [200, "image/png"], camapi)
check("only cameras can be fetched", pg13.evaluate("fetch('api/camera/light.x').then(r => r.status)") == 400)
rid = pg13.evaluate("""() => {
  const f = window.__fp.layout.floors[window.__fp.floorIdx()], r = f.rooms[0];
  const xs = r.points.map(p => p[0]), zs = r.points.map(p => p[1]), cx = (Math.min(...xs) + Math.max(...xs)) / 2, cz = (Math.min(...zs) + Math.max(...zs)) / 2;
  f.devices.push({id: 'tcam', type: 'camera', x: cx, z: cz, y: 2.2, rot: 0, scale: 1, name: 'Cam', entity: 'camera.flur', fov: 90, range: 3, motionEntity: 'binary_sensor.rauch'},
                 {id: 'tlt', type: 'light', x: cx + 0.5, z: cz + 0.5, y: 2.5, rot: 0, scale: 1, name: 'L', entity: 'light.wohnzimmer'});
  window.__fp.rebuild();
  return r.id;
}""")
pg13.wait_for_timeout(500)
check("camera shows its field of view as a cone", pg13.evaluate("window.__fp.coneScreen('tcam')") is not None)
c0 = pg13.evaluate("window.__fp.coneScreen('tcam')")
cam0 = pg13.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].devices.find(d => d.id === 'tcam')")
pg13.evaluate(f"window.__fp.moveDevice('tcam', {cam0['x'] + 0.8}, {cam0['z'] + 0.6})"); pg13.wait_for_timeout(400)
c1 = pg13.evaluate("window.__fp.coneScreen('tcam')")
check("the cone moves along when the camera is moved", c1 and abs(c1["x"] - c0["x"]) + abs(c1["y"] - c0["y"]) > 8, (c0, c1))
pg13.evaluate(f"window.__fp.moveDevice('tcam', {cam0['x']}, {cam0['z']})"); pg13.wait_for_timeout(300)
cc = pg13.evaluate("window.__fp.coneScreen('tcam')")
pg13.click('[data-mode="live"]'); pg13.wait_for_timeout(600)
hc = pg13.evaluate(f"window.__fp.liveHitAt({cc['x']}, {cc['y']})") if cc else None
check("camera cone (#234): no hit box in live mode, only the camera itself", cc is not None and (hc or {}).get("id") != "tcam", (cc, hc))
pg13.click('[data-mode="edit"]'); pg13.wait_for_timeout(600)
pg13.evaluate("() => { window.__fp.layout.floors[window.__fp.floorIdx()].devices.find(d => d.id === 'tcam').fov = 0; window.__fp.rebuild(); }"); pg13.wait_for_timeout(300)
check("field of view 0 means no cone", pg13.evaluate("window.__fp.coneScreen('tcam')") is None)
pg13.click('[data-mode="live"]'); pg13.wait_for_timeout(800)
pg13.evaluate(f"window.__fp.openRoomPanel('{rid}')"); pg13.wait_for_timeout(800)
heads = " ".join(pg13.locator("#roomPanel h4").all_inner_texts())
check("room panel: groups by kind (lights, cameras)", "LIGHTS" in heads and "CAMERAS" in heads, heads)
check("room panel: slide switch instead of a toggle button", pg13.locator("#roomPanel .sw input").count() >= 1)
check("room panel: camera picture", pg13.locator("#roomPanel img.rp-cam").count() == 1)
check("cameras button at the top shows the camera", pg13.locator("#camPill").is_visible() and "1" in pg13.inner_text("#camPill"))
urllib.request.urlopen(HA + "/_set?e=binary_sensor.rauch&s=on"); pg13.wait_for_timeout(1800)
camtxt = pg13.inner_text("#camPill")
check("cameras button says where movement was detected", pg13.locator("#camPill.alert").count() == 1 and "Motion detected" in camtxt, camtxt)
pg13.click("#camPill"); pg13.wait_for_timeout(600)
check("cameras overview: grouped by room, the room with movement marked", pg13.locator("#camGrid .camGroup.alert").count() == 1 and pg13.locator("#camGrid .camGroupHead").count() == 1)
check("cameras overview: a card with a picture per camera", pg13.locator("#camGrid .camCard").count() == 1 and pg13.locator("#camGrid img.cam-big").count() == 1)
check("cameras overview: button straight to the Home Assistant entity", pg13.locator("#camGrid .haBtn").count() == 1)
pg13.keyboard.press("Escape"); pg13.wait_for_timeout(300)
urllib.request.urlopen(HA + "/_set?e=binary_sensor.rauch&s=off"); pg13.wait_for_timeout(1000)
pg13.click('[data-mode="edit"]'); pg13.wait_for_timeout(300)
# --- automatic rooms (#17): delete the rooms of a floor, the closed wall loops bring them back
nr = pg13.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].rooms.length")
pg13.evaluate("() => { window.__fp.layout.floors[window.__fp.floorIdx()].rooms.length = 0; window.__fp.rebuild(); }"); pg13.wait_for_timeout(300)
pg13.click("#autoRooms"); pg13.wait_for_timeout(400)
nr2 = pg13.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].rooms.length")
check("automatic rooms: every closed wall loop becomes a room", nr > 0 and nr2 == nr, (nr, nr2))
pg13.click("#autoRooms"); pg13.wait_for_timeout(300)
check("automatic rooms: a second run adds nothing", pg13.evaluate("window.__fp.layout.floors[window.__fp.floorIdx()].rooms.length") == nr2)
check("garage door is in the palette", pg13.locator('#openingPalette button[data-opening="doorGarage"]').count() == 1)
pg13.evaluate("() => { const f = window.__fp.layout.floors[window.__fp.floorIdx()]; f.walls.forEach(w => { if (w.openings.length === 0) w.openings.push({id: 'tgate', type: 'door', style: 'garage', pos: 1, width: 0.6, height: 2.1, sill: 0, entity: 'cover.rollo', name: 'Tor'}); }); window.__fp.rebuild(); }"); pg13.wait_for_timeout(400)
check("garage door is built (rolls up, 1 = closed)", pg13.evaluate("(() => { let r = null; window.__fp.scene.traverse(o => { if (o.userData && o.userData.id === 'tgate' && o.userData.pivot) r = o.userData.pivot.scale.y; }); return r; })()") == 1)
check("frameless opening is in the palette", pg13.locator('#openingPalette button[data-opening="doorGap"]').count() == 1)
pg13.click('#modeBar [data-vm="co2"]'); pg13.wait_for_timeout(400)
check("CO2 colouring: button and colour scale", pg13.locator("#viewLegend").is_visible() and "ppm" in pg13.inner_text("#viewLegend"))
pg13.click('#modeBar [data-vm="normal"]'); pg13.wait_for_timeout(300)
check("CO2 colouring: scale gone in normal view", not pg13.locator("#viewLegend").is_visible())
view_menu(pg13)
check("pull apart: no button in the floor view", not pg13.locator("#explodeToggle").is_visible())
pg13.click("#floorRail .railHouse"); pg13.wait_for_timeout(800)
gaps_js = "(() => { const f = window.__fp, n = f.layout.floors.length, r = []; for (let i = 1; i < n; i++) r.push(f.elev(i) - f.elev(i - 1)); return r; })()"
gap0 = pg13.evaluate("window.__fp.elev(2) - window.__fp.elev(1)")
gaps0 = pg13.evaluate(gaps_js)
view_menu(pg13); pg13.click("#explodeToggle"); pg13.wait_for_timeout(1200)
gap1 = pg13.evaluate("window.__fp.elev(2) - window.__fp.elev(1)")
gaps1 = pg13.evaluate(gaps_js)
check("pull apart: floors get a gap in the whole-house view", pg13.locator("#explodeToggle").is_visible() and gap1 > gap0 + 1, (gap0, gap1))
check("pull apart: EVERY floor is lifted off the one below (also the ground floor off the basement)", len(gaps1) >= 2 and all(g1 > g0 + 1 for g0, g1 in zip(gaps0, gaps1)), (gaps0, gaps1))
view_menu(pg13); pg13.click("#explodeToggle"); pg13.wait_for_timeout(600)
check("pull apart: stacked again", abs(pg13.evaluate("window.__fp.elev(2) - window.__fp.elev(1)") - gap0) < 1e-6 and pg13.evaluate(gaps_js) == gaps0)
pg13.close()
# --- view menu in the bottom bar, half section hides what hangs above the cut, see-through walls, a second tap leaves the room (#132, #131, #129, #128)
pgW = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgW.goto(BASE + "?debug=1&mode=edit"); pgW.wait_for_timeout(2500)
check("view menu: the button sits in the bottom bar with the colour buttons", pgW.evaluate("!!document.querySelector('#modeBar #viewMenuBtn')"))
pgW.click("#viewMenuBtn"); pgW.wait_for_timeout(200)
check("view menu: it opens above the bottom bar", pgW.evaluate("(() => { const a = document.querySelector('#viewMenu').getBoundingClientRect(), b = document.querySelector('#viewMenuBtn').getBoundingClientRect(); return a.height > 0 && a.bottom <= b.top + 2 && a.top >= 0; })()"))
pgW.click('#modeBar [data-vm="temp"]'); pgW.wait_for_timeout(200)
check("view menu: the colour buttons still switch the colouring", "active" in (pgW.get_attribute('#modeBar [data-vm="temp"]', "class") or "") and "active" not in (pgW.get_attribute("#viewMenuBtn", "class") or "").replace("pill", ""))
pgW.click('#modeBar [data-vm="normal"]'); pgW.wait_for_timeout(200)
pgW.evaluate("() => { const f = window.__fp.layout.floors[window.__fp.floorIdx()]; f.devices.push({id: 'cutLamp', type: 'light', x: 0, z: 0, y: 2.4, rot: 0, scale: 1, name: 'Decke', entity: ''}, {id: 'cutLow', type: 'plant', x: 1, z: 1, y: 0, rot: 0, scale: 1, name: 'Boden', entity: ''}); window.__fp.rebuild(); }")
pgW.wait_for_timeout(500)
view_menu(pgW); pgW.click("#halfToggle"); pgW.wait_for_timeout(800)
check("half section: a lamp that hangs above the cut is hidden, a plant on the floor stays", not pgW.evaluate("window.__fp.isShown('cutLamp')") and pgW.evaluate("window.__fp.isShown('cutLow')"))
view_menu(pgW); pgW.click("#halfToggle"); pgW.wait_for_timeout(800)
check("half section: off again, the lamp is back", pgW.evaluate("window.__fp.isShown('cutLamp')"))
pgW.close()
box_js = "() => { const f = window.__fp.layout.floors[window.__fp.floorIdx()]; f.walls.length = 0; f.devices.length = 0; [[[0,0],[6,0]],[[6,0],[6,5]],[[6,5],[0,5]],[[0,5],[0,0]]].forEach((w, i) => f.walls.push({id: 'sw' + i, a: w[0], b: w[1], thickness: 0.2, height: 2.6, openings: []})); window.__fp.rebuild(); }"
walls_js = "(() => { let minOp = 1, minScale = 1; window.__fp.scene.traverse(o => { if (o.userData && o.userData.kind === 'wall') { minScale = Math.min(minScale, o.scale.y); o.traverse(c => { if (c.material) [].concat(c.material).forEach(m => { minOp = Math.min(minOp, m.opacity); }); }); } }); return [minOp, minScale]; })()"
set_setting("seeThrough", True)
pgS = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgS.goto(BASE + "?debug=1&mode=edit"); pgS.wait_for_timeout(2000)
pgS.evaluate(box_js); pgS.wait_for_timeout(2500)
op, sc = pgS.evaluate(walls_js)
pgS.close()
set_setting("seeThrough", False)
pgS2 = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgS2.goto(BASE + "?debug=1&mode=edit"); pgS2.wait_for_timeout(2000)
pgS2.evaluate(box_js); pgS2.wait_for_timeout(2500)
op2, sc2 = pgS2.evaluate(walls_js)
check("see-through walls: walls facing the camera fade (clearly more than with the option off) and are not lowered", op < op2 - 0.2 and sc > 0.99, (op, sc, op2))
check("see-through walls: off, the walls keep their own opacity", op2 > 0.7, (op2, sc2))
check("see-through walls: on, the fade goes down to about 30 %", op < 0.35, op)
pgS2.close()
pgM = b.new_page(viewport={"width": 1400, "height": 850}, extra_http_headers={"X-Remote-User-Name": "admin"})
pgM.goto(BASE + "?debug=1&mode=edit"); pgM.wait_for_timeout(2500)
check("see-through: the View menu has its own button for it", pgM.evaluate("!!document.querySelector('#viewMenu #seeToggle')"))
pgM.evaluate("window.__fp.addRoofForTest()"); pgM.wait_for_timeout(300)
pgM.click("#floorRail .railHouse"); pgM.wait_for_timeout(1000)
pgM.evaluate("window.__fp.camFar()"); pgM.wait_for_timeout(800)
f_off = pgM.evaluate("window.__fp.roofFactor()")
view_menu(pgM); pgM.click("#seeToggle"); pgM.wait_for_timeout(1200)
pgM.evaluate("window.__fp.camFar()"); pgM.wait_for_timeout(1500)
f_on = pgM.evaluate("window.__fp.roofFactor()")
pgM.evaluate("window.__fp.switchFloor(window.__fp.layout.floors.length - 1)"); pgM.wait_for_timeout(600)
pgM.evaluate("window.__fp.camAt(window.__fp.cam()[0], window.__fp.cam()[1], window.__fp.cam()[2])")
pgM.evaluate("() => { for (let i = 0; i < 60; i++) window.__fp.frame(); }"); pgM.wait_for_timeout(300)
f_edit = pgM.evaluate("window.__fp.roofFactor()")
check("see-through: while the roof is edited (roof floor open) the roof stays clearly visible, also close up", f_edit >= 0.8, f_edit)
check("see-through: the button turns the option on", pgM.evaluate("window.__fp.settings().seeThrough") is True and "active" in (pgM.get_attribute("#seeToggle", "class") or ""))
check("see-through: the roof is see-through from afar too (it hides nothing behind it)", f_off > 0.9 and f_on < 0.4, (f_off, f_on))
check("see-through: switching it on switches Auto off", pgM.evaluate("window.__fp.settings().cutaway") is False and "active" not in (pgM.get_attribute("#autoToggle", "class") or ""))
view_menu(pgM); pgM.click("#autoToggle"); pgM.wait_for_timeout(900)
check("see-through: switching Auto on switches see-through off", pgM.evaluate("window.__fp.settings().cutaway") is True and pgM.evaluate("window.__fp.settings().seeThrough") is False and "active" not in (pgM.get_attribute("#seeToggle", "class") or ""))
pgM.close()
